### ISSUE TITLE
List of tables is empty

### ISSUE THREAD

**Issue by habamax** [kristijanhusak/vim-dadbod-ui#1]
neovim/vim on win10, postgres 10.12

![image](https://user-images.githubusercontent.com/234774/77634946-d8066f80-6f62-11ea-9ec7-faa0f3024916.png)

There are ~10 tables in a database mdm_stage schema

**Comment by kristijanhusak** [comment]
Which database type is this (mysql, postgres) ?

For the tables, try this:
1. set `let b:db = 'yourdburl'`
2. Write `:DB ` in command and press tab. Do you get autocompletion with table names? I'm using dadbods function to grab tables, so if it's not working as autocompletion than it needs to be fixed in dadbod.

**Comment by habamax** [comment]
> Which database type is this (mysql, postgres) ?

postgres 10.12

![image](https://user-images.githubusercontent.com/234774/77636717-94f9cb80-6f65-11ea-91e5-299e085ffaa3.png)

**Comment by habamax** [comment]
Note that `:DB select * from mytable` works, but `:DB <tab>` shows list of database connection types

**Comment by habamax** [comment]
And I couldn't find in vim-dadbod documentation that `DB` command should return list of tables...

**Comment by kristijanhusak** [comment]
I explained wrong. Try this:

```
:DB b:db <TAB>
```

**Comment by habamax** [comment]
> 
> 
> I explained wrong. Try this:
> 
> ```
> :DB b:db <TAB>
> ```

I can see it tries to do smth (blinking ...) and nothing happens :(

**Comment by kristijanhusak** [comment]
Yeah looks like dadbod is also not able to find the tables, since it should give you autocomplete with table names. It's really strange that it doesn't work for postgres, on my 9.6 version everything works fine. Don't think it has anything to do with postgres version though.

**Comment by habamax** [comment]
I suspect that it is somehow related to default schema.

I don't have default `public` schema and probably it tries to search tables there.

Is there a way to set default schema on a connection string though?

**Comment by kristijanhusak** [comment]
What do you get when you execute this in your terminal:
```
psql --dbname='postgres://your-db-url' --no-psqlrc -tA -c "\dtvm"
```

**Comment by habamax** [comment]
> I don't have default `public` schema and probably it tries to search tables there.

Tried with database that has `public` and it doesn't work neither.

**Comment by habamax** [comment]
> psql --dbname='postgres://your-db-url' --no-psqlrc -tA -c "\dtvm"

PS C:\Users\maksim.kim> psql --dbname='postgres://localhost:5432/postgres' --no-psqlrc -tA -c "\dtvm"
psql: FATAL:  role "maksim.kim" does not exist

**Comment by habamax** [comment]
> 
> 
> What do you get when you execute this in your terminal:
> 
> ```
> psql --dbname='postgres://your-db-url' --no-psqlrc -tA -c "\dtvm"
>
 ```

```
psql --dbname='postgres://mdm:pass@localhost:5432/mdm' --no-psqlrc -tA -c "\dtvm"
Отношения не найдены. (Relations are not found)
```

**Comment by kristijanhusak** [comment]
According to this, you should get some tables for the command with `postgres://postgres:@localhost:5432/postgres`.

Try `:DB postgres://postgres:@localhost:5432/postgres <TAB>` and see if you get anything.

**Comment by habamax** [comment]
> 
> 
> According to this, you should get some tables for the command with `postgres://postgres:@localhost:5432/postgres`.
> 
> Try `:DB postgres://postgres:@localhost:5432/postgres <TAB>` and see if you get anything.

Nothing -- again 3 dots and nothing.

But queries works `:DB postgres://postgres:@localhost:5432/postgres select * from test` returns result.

**Comment by habamax** [comment]
I guess it is upstream issue then :(

**Comment by kristijanhusak** [comment]
Yeah probably. I assume Windows is generally not so much covered and tested for these cases.

**Comment by habamax** [comment]
Fixed upstream
