### ISSUE TITLE
Mysql password warning instead of table names

### ISSUE THREAD

**Issue by rakshans1** [kristijanhusak/vim-dadbod-ui#10]
![image](https://user-images.githubusercontent.com/12949352/79719727-cbc0c880-82fc-11ea-8c11-e696bd198609.png)

**Comment by kristijanhusak** [comment]
Can you give me the format of database url that you are using?
Also, give me some system info, OS, Vim/Neovim version, etc.

**Comment by rakshans1** [comment]
url: mysql://user:password@domain.com
NVIM: v0.5.0-nightly-1-gdc0e534
OS: Ubuntu 18.04.4 LTS x86_64
Shell: zsh 5.4.2

**Comment by kristijanhusak** [comment]
Since connections are per db, and your url doesn't contain database name, I suggest to add a db name to the url like this:
```
mysql://user:password@domain.com/db_name
```
Let me know if that fixes it completely, since i'm not sure about the warning.

**Comment by rakshans1** [comment]
Can I use my own `.sql` file and run query by selecting a line

**Comment by kristijanhusak** [comment]
You can assign your sql file to a certain database as a buffer with `:DBUIFindBuffer`, which will set `b:db`, that you can use directly with dadbod (by selecting lines and executing `:DB` on them). Just make sure to update.
