### ISSUE TITLE
[FeatureRequest] support comment line in buffer

### ISSUE THREAD

**Issue by hiberabyss** [kristijanhusak/vim-dadbod-ui#100]
For some db like `redis`, there is no built-in comment line support.

Is it possible to support comment line in dadbod-ui buffer? Only non-comment lines send to db when write the file.

**Comment by kristijanhusak** [comment]
There's no any syntax support for any DB type as part of this plugin. For all sql databases I just use builtin filetypes (sql,mysql,plsql), which are already part of Vim. What filetype do you use when you write redis outside of dadbod-ui?

**Comment by hiberabyss** [comment]
> There's no any syntax support for any DB type as part of this plugin. For all sql databases I just use builtin filetypes (sql,mysql,plsql), which are already part of Vim. What filetype do you use when you write redis outside of dadbod-ui?

Both `sql` (with `--` as comment string) or `conf` (with `#` as comment string) should be OK.

Maybe we could specify custom filetype in `g:dbs`, and the comment string is determined by vim.

**Comment by kristijanhusak** [comment]
We can set that up, but I don't know what filetype is being used for redis in vim?

**Comment by hiberabyss** [comment]
Another way is to specify custom range specifier instead of the default `%` (e.g. `.`), which could temporarily solve the problem.

**Comment by kristijanhusak** [comment]
You can run parts of the query with `<Leader>S`. See https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L322

**Comment by hiberabyss** [comment]
> We can set that up, but I don't know what filetype is being used for redis in vim?

Also did not know if there is redis filetype in vim, only connect redis in vim with vim-dadbod-ui.

Thanks for your great work!

**Comment by hiberabyss** [comment]
> You can run parts of the query with `<Leader>S`. See https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L322

Sometimes I would like to write many queries in file and run chosen query one time, however, all queries will be run when write file.

Could there be a new mapping which only run the current line? It will be better if the map support text object.

**Comment by kristijanhusak** [comment]
You can run current line with this command:
```
:.DB
```

Or you do a visual select of query that you want to run, press `:` and type `DB`, which produces this:
```
:'<,'>DB
```
Then run it.
