### ISSUE TITLE
How to use query param like vim-dadbod in this plugins?

### ISSUE THREAD

**Issue by sheenazien8** [kristijanhusak/vim-dadbod-ui#103]
I found error `Error connecting to db Homestead: DB exec error: mysql: [Warning] Using a pass
word on the command line interface can be insecure.^@ERROR 2003 (HY000): Can't
 connect to MySQL server on '192.168.10.10' (111)`

**Comment by kristijanhusak** [comment]
Is your vim-dadbod working fine?

Try this:
```
:DB your_db_url_here select * from some_table
```

**Comment by sheenazien8** [comment]
working fine when i use this. `:DB mysql:--login-path=homestead use lakasir; select * from users;`
but when i use `DB mysql://homestead:secret@192.168.10.10:3360/lakasir select * from users;` i found errors

**Comment by kristijanhusak** [comment]
try doing `localhost` instead of the ip.

**Comment by sheenazien8** [comment]
in this case i want connect mysql in my vagrant / VM

**Comment by kristijanhusak** [comment]
Try connecting without the password:
```
DB mysql://homestead@192.168.10.10:3360/lakasir select * from users;
```
It should prompt you to enter the password.

**Comment by sheenazien8** [comment]
i found this errors 
![Screenshot from 2021-07-23 16-36-29](https://user-images.githubusercontent.com/37477023/126764166-0b4befe1-30c9-439e-9256-9cee9926d1cb.png)

**Comment by kristijanhusak** [comment]
Your vagrant ip seems wrong.

**Comment by sheenazien8** [comment]
in [Vim-dadbod](https://github.com/tpope/vim-dadbodl) i can connect with query params, but when i wanna use vim-dadbod-ui i can't connect with query parmas

**Comment by sheenazien8** [comment]
> Your vagrant ip seems wrong.

No. because i can connect with this command `DB mysql:--login-path=homestead use lakasir; select * from users;`

**Comment by kristijanhusak** [comment]
Try defining your connection url like that and see if it works: `mysql:--login-path=homestead use lakasir;`

**Comment by sheenazien8** [comment]
when i add new connection, and access the new connection, i got this errors 
![Screenshot from 2021-07-23 16-50-39](https://user-images.githubusercontent.com/37477023/126765752-4d90087d-15a2-4e6f-818e-c11f877cadfb.png)

and i try check in this file `~/.local/share/db_ui/connections.json` my new connection is created like this ```
	{
		"url": "mysql:///--login-path%3Dhomestead",
		"name": "Homestead"
	}
```

**Comment by kristijanhusak** [comment]
I'll open upstream issue. I'm using dadbod's function that converts it to this.

**Comment by kristijanhusak** [comment]
Does your query work when you do this?

```
DB mysql:///--login-path%3Dhomestead select * from users
```

**Comment by sheenazien8** [comment]
error, but it tries to connect to localhost instead of vagrant, `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
`

**Comment by kristijanhusak** [comment]
Does same thing happens with this?
```
DB mysql:///--login-path%3Dhomestead use lakasir;select * from users
```

**Comment by sheenazien8** [comment]
it works!

**Comment by sheenazien8** [comment]
but why when i use DBUI it didnt works

**Comment by kristijanhusak** [comment]
I'm not sure if it will work, but try adding your connection with the `use lakasir` part:

```
mysql:///--login-path%3Dhomestead use lakasir;
```

It would be best to just figure out the proper connection url. Can you also try adding this as connection?
```
mysql://homestead@192.168.10.10:3360/lakasir?login-path=homestead
```

**Comment by sheenazien8** [comment]
`mysql:///--login-path%3Dhomestead use lakasir;` error acces denied

`mysql://homestead@192.168.10.10:3360/lakasir?login-path=homestead` error can't connect to MySQL server 192.168.10.10

**Comment by kristijanhusak** [comment]
From what I see in the docs [here](https://laravel.com/docs/4.2/homestead#daily-usage)
Your url should be something like this (if you didn't change any defaults):

```
mysql://homestead:secret@127.0.0.1:33060/lakasir
```

**Comment by sheenazien8** [comment]
i got still same error 
```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2007 (HY000): Protocol mismatch; server version = 11, client version = 10
```

**Comment by kristijanhusak** [comment]
I suggest figuring out the ip of the vagrand machine and apply that to the example from my previous comment. You can figure out the ip with this (haven't tried): https://stackoverflow.com/a/41251906/1474465

Than just use the ip in here:
```
mysql://homestead:secret@IP_HERE:33060/lakasir
```
