### ISSUE TITLE
switch mongo db

### ISSUE THREAD

**Issue by zhaogangang** [kristijanhusak/vim-dadbod-ui#104]
how to switch mongo db in UI, just like mysql

**Comment by kristijanhusak** [comment]
You'll have to be more precise, I don't know what you mean by "switch".

**Comment by zhaogangang** [comment]
![dadbod](https://user-images.githubusercontent.com/44504986/126858936-360fbc8e-c7a8-459e-9842-14bc42f03e84.png)

here is two database tree structure  in dadbod-ui, i want to mongo is like mysql, just can switch database in dadbod-ui. but now, mongo database in dadbod-ui is selected when connected to mongod and can't change

**Comment by zhaogangang** [comment]
my dadbod-ui setting is follow

let g:dbs = [
            \{"url": "mysql://root:root@localhost:3306", "name": "mysql-local"},
            \{"url": "mongodb://:@localhost:27017", "name": "mongo-local"}
            \]

**Comment by kristijanhusak** [comment]
As far as I know Mongo does not have schemas. You will have to add those as separate entries.
I didn't do much for mongo integration, I'm not using it on daily basis. If you think it can be improved feel free to submit a PR.

**Comment by zhaogangang** [comment]
oh ~, i see, thank you for your answer.
