### ISSUE TITLE
On Windows 10: "E212: Can't open file for writing: no such file or directory"

### ISSUE THREAD

**Issue by dhazel** [kristijanhusak/vim-dadbod-ui#105]
OS: Windows 10
Sql server: MS SQL Server

When executing a query, the query returns successfully and successfully writes the `.dbout` file and the `.sql` file in a temporary folder; however, I also receive the following error message.

    E212: Can't open file for writing: no such file or directory

I am happy to help debug this if you have pointers on where to look first.

**Comment by kristijanhusak** [comment]
Is dbout buffer properly shown, no issues there?
Can you try adding `g:db_ui_debug = 1` to your vimrc, reproduce the query and give me the output?

**Comment by dhazel** [comment]
Yeah, the dbout buffer is properly shown.

With `g:db_ui_debug = 1` I now get the following output in `:messages`

    E212: Can't open file for writing: no such file or directory
    [DBUI Debug] {'message': 'Executing whole buffer', 'command': '%DB'}

**Comment by kristijanhusak** [comment]
Do you get the same error when you open up the query buffer and execute `:%DB` command? Or only when you write it ?

**Comment by dhazel** [comment]
I get that error only when I write the file (`:w`), not when I execute `:%DB`

**Comment by kristijanhusak** [comment]
What is the full path of the temporary sql buffer generated? 
Can you check if it's writable like this?
```
echo writable('/path/to/the/tmp/file')
```

**Comment by dhazel** [comment]
Here is the full path:
    C:\Users\myusername\AppData\Local\Temp\nvimEYeCka\dev-Date-List-2021-08-02 08:16:25

Those colons may be disallowed characters in windows file names?

And the filewritable check:

    echo filewritable("C:\Users\myusername\AppData\Local\Temp\nvimEYeCka\dev-Date-List-2021-08-02 08:16:25")
    > 0

**Comment by kristijanhusak** [comment]
Yeah, maybe.

Can you try adding this to your vimrc and see if it helps?
```vim
function s:buffer_name_generator(opts)
  if empty(a:opts.table)
    return 'myquery-'.localtime()
  endif
  return 'myquery-fortable-'.a:opts.table.'-'.localtime()
endfunction

let g:Db_ui_buffer_name_generator = function('s:buffer_name_generator')
```

This should make tmp filenames without the colons.

**Comment by dhazel** [comment]
That solves the issue!

**Comment by dhazel** [comment]
I successfully got the date formatting to work as before by replacing the colon with an identical looking digraph.

    strftime('%d-%m-%y %H∶%M∶%S')

**Comment by kristijanhusak** [comment]
I'll add a  check and format names differently for windows. Thanks for debugging.

**Comment by kristijanhusak** [comment]
I pushed a fix that uses the digraph. Can you please let me know if it's working now?

**Comment by dhazel** [comment]
Your update works great on my box.

Thanks for your DB tools! Great stuff.
