### ISSUE TITLE
control result auto-folding and auto switch bewteen windows

### ISSUE THREAD

**Issue by guerbai** [kristijanhusak/vim-dadbod-ui#107]
Thank you for developing this wonderful plugin.
When I try to use it, I think there may be something that can be more efficient 

1. When I execute a query, my result always folds automatically, so that I have to jump to the dbout file and use `zR` to see the result detail, like this picture.
![image](https://user-images.githubusercontent.com/17327981/129072411-3a5b5a2f-a5bd-4803-ad2e-262220987954.png)
Those actions increase operating costs. Is it possible to supply a setting to control this auto-folding behavior?

2. After execute a query, the cursor is still in the query window, it may be more efficient for user if dadbod-ui can auto put the cursor at dbout window after executing

**Comment by martinbjeldbak** [comment]
Sorry to necropost: for anyone finding this from a search engine - heres how you could do this in a lua-based vim config

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "dbout",
  callback = function()
    vim.opt_local.foldenable = false
  end,
})
```
