### ISSUE TITLE
Adding wrong url results in an error and can't open drawer again

### ISSUE THREAD

**Issue by SimeonAleksov** [kristijanhusak/vim-dadbod-ui#109]
Simple steps to reproduce: Just mistype a connection url(extra slash for ex) and toggle 
This is the error: 
```
Error detected while processing function db_ui#toggle:
line    2:
E121: Undefined variable: drawer
E15: Invalid expression: s:dbui_instance.drawer.toggle()
```
Is there any fix for this? I reinstalled and everything, still same.
Maybe first test the connection then add it if its ok?

**Comment by SimeonAleksov** [comment]
Looks like there already was an [issue](https://github.com/kristijanhusak/vim-dadbod-ui/issues/69) about this, removing the json file, does reset it, however this shouldn't really happen?

**Comment by SimeonAleksov** [comment]
Any updates?

**Comment by kristijanhusak** [comment]
Sorry, still didn't look into this. Is this something that happens to you often? Seems like an edge case.

**Comment by FCO** [comment]
Try using a password containing `@`.
