### ISSUE TITLE
Help Connecting to a Postgres DB inside a Docker Container

### ISSUE THREAD

**Issue by jonathan-raines** [kristijanhusak/vim-dadbod-ui#113]
Hello!

Loving the plugin, but recently ran into some trouble. The plugin config worked great when I was running the DB locally, but now I have needed to move to the development DB living inside a Docker container. I can access the container through localhost:5433 and I can connect successfully to that port. However I cannot find any information about any of the databases that I have in the container.

This is my variable setup. I'm hoping I could get some guidance on how to configure this properly.

`       let g:dbs = [
        \ { 'name': 'docker pg', 'url': 'postgres://postgres:welcome@localhost:5433'},
        \ ]
`

![image](https://user-images.githubusercontent.com/5840124/139952193-b42f6c3f-e552-482d-86c9-1b8d25e6513b.png)

![image](https://user-images.githubusercontent.com/5840124/139952279-439d14e8-4603-4678-abf1-5681cae3af36.png)

I can't find my actual tables anywhere.

If there's any other info I can provide, please let me know. Thank you!

**Comment by kristijanhusak** [comment]
You should provide database name at the end: `postgres://postgres:welcome@localhost:5433/dbname`. I'm assuming you are using official image https://hub.docker.com/_/postgres . In here it says this for db name:
```
POSTGRES_DB
This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.
```

So if you didn't provide anything for `POSTGRES_DB` when creating an image, your db name should be `postgres`: `postgres://postgres:welcome@localhost:5433/postgres`.

How did you exactly use postgres locally without the database name? Maybe not providing the database falls back to the `postgres`, but I'm not sure.

**Comment by jonathan-raines** [comment]
`How did you exactly use postgres locally without the database name?`

I used the AddConnection and specified the database name. I tried using the default postgres and the actual database name found by using `psql \l` and I get the same as above.

Trying to access the docker databases, I don't show any public schemas. Do you think it's a docker configuration issue?

**Comment by kristijanhusak** [comment]
I'm not sure how your dockerfile looks, but you probably need to expose port `5432` from it, or to bind it when running/building the container.

**Comment by jonathan-raines** [comment]
Is there a way to select a particular database when there is more than one in the schema?

**Comment by kristijanhusak** [comment]
If you have multiple shemas in same database you should be able to view all of them. For example by default you should have something like `information_schema` and `pg_catalog` and `public`. There is currently no way to list all databases on specific connection with dbui, you have to add them separately.

**Comment by jonathan-raines** [comment]
Issue was on the docker's database configuration instead. Plugin works as intended
