### ISSUE TITLE
How can I just save the file and it work as expected

### ISSUE THREAD

**Issue by tin-pham** [kristijanhusak/vim-dadbod-ui#118]
I must save and quit buffer to make it work properly. Unless it will execute the buffer twice. 

![image](https://user-images.githubusercontent.com/20679090/144008288-ecf854d5-c304-4983-bb11-898f84d6f7af.png)

**Comment by kristijanhusak** [comment]
What you mean it executes the buffer twice?

**Comment by tin-pham** [comment]
> What you mean it executes the buffer twice? 

I add the age column to table, but it give me error because i have already added, but im not. 

Same when i create table, it tell me the table exist ?, just like it happen twice, it create the table and execute it again.

Maybe i miss use this plugin or something.

**Comment by tin-pham** [comment]
See this didn't have any age column
![image](https://user-images.githubusercontent.com/20679090/144035849-79fc1524-a629-4973-a299-cf197d9fe523.png)
I add that and it give me error 'already exists'
![image](https://user-images.githubusercontent.com/20679090/144036069-a9fe63ef-8f0c-46fa-be37-e133857b613f.png)

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/144036160-e0c4bcc6-c311-4f0b-8cb3-c6df4c226382.png)

**Comment by tin-pham** [comment]
I think I know the problem, that because the sql-formatter, i turn off it and now it work

**Comment by kristijanhusak** [comment]
@tin-pham how are you running the formatter? Give me the code that triggers it.

**Comment by tin-pham** [comment]
I used this https://github.com/zeroturnaround/sql-formatter

Basictly when I save a file it will format and write to the file with the -o  to the tmp directory where it was store the sql file 

-t mean indent with tab, and -u is uppercase

![image](https://user-images.githubusercontent.com/20679090/144040212-11a6b9ce-4ecb-47bb-bbaf-90c2b94dc845.png)

**Comment by kristijanhusak** [comment]
Ok, but how are you running this function, which some other plugin? If you can give me the link to your dotfiles.

**Comment by tin-pham** [comment]
https://github.com/tin-pham/NeoVimLua

Thanks the format inside lua/format-config

**Comment by kristijanhusak** [comment]
Ok, you are using https://github.com/lukas-reineke/format.nvim from what I see. You can either update this line (https://github.com/tin-pham/NeoVimLua/blob/master/lua/format-config/init.lua#L35) to use `BufWritePre` ( I don't know if this would work though):
```vim
vim.cmd('autocmd BufWritePre * FormatWrite')
```

Or to not trigger any other autocmds while doing format. I think this should work

```vim
vim.cmd('autocmd BufWritePost * noau FormatWrite')
```

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/144044754-94b7b315-a301-4b3d-8b83-1f2da45fd46b.png)
It still not work, I try either. Do it have something to do with filetype, because right now the file type DBUI create don't have '.sql' extension

**Comment by kristijanhusak** [comment]
You can disable automatic execution of the query on save with [this variable](https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L507):
```lua
vim.g.db_ui_execute_on_save = 0
```

Then when you want it to be executed, you can trigger [specific mapping](https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L322) for it, which is `<leader>S` by default (uppercase S).

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/144052965-aa62e194-c753-4dc9-a343-3285734d0447.png)

Thanks, now it work, need to edit the format filetype. I think it better to generate the .sql file format filetype, but anyway, thanks ^ ^ it work
