### ISSUE TITLE
Fields larger than necessary in results window

### ISSUE THREAD

**Issue by SaintRyoh** [kristijanhusak/vim-dadbod-ui#120]
![issue](https://user-images.githubusercontent.com/14931827/145924363-d832ad1d-5b48-4b7a-ac20-e028b7928595.png)

Greetings, I just started using dadbod-ui on NixOs.  I'm experiencing a weird issue where the column widths in the results pane are much larger than necessary for each column. Attached is an example of the problem. The result is that I need to scroll horizontally quite a bit to see all the columns.

Thanks for the excellent plugin!

**Comment by kristijanhusak** [comment]
Hi, this is not controlled by dbui. That's just how the program outputs it (looks like mssql).

**Comment by SaintRyoh** [comment]
Thank you for your response. I was able to find some options in sqlcmd for controlling that here: https://stackoverflow.com/questions/33738433/how-to-format-sqlcmd-output 
Do you know of a way in DB or DBUI to send these additional parameters to sqlcmd?

**Comment by kristijanhusak** [comment]
I don't know if sqlcmd supports something like postges support with `.psqlrc`. If that exists, you could maybe do something, if not I'm not sure what's the best way to tackle this.

**Comment by juancarlis** [comment]
@SaintRyoh could you solve it?
