### ISSUE TITLE
Can't open transaction in PostgreSQL

### ISSUE THREAD

**Issue by tin-pham** [kristijanhusak/vim-dadbod-ui#122]
It work on psql 
![image](https://user-images.githubusercontent.com/20679090/148138720-8835fed7-ac6d-413e-97ab-fa03d94ef85f.png)

On dadbodui 
![image](https://user-images.githubusercontent.com/20679090/148138770-96a3f36d-b145-4510-b1a8-ee4003df94af.png)
![image](https://user-images.githubusercontent.com/20679090/148138802-d23853bf-45ba-4ce2-af20-5d5bcd31aab4.png)
![image](https://user-images.githubusercontent.com/20679090/148138820-a8736eac-8263-494a-8d05-bc252e7d8cb8.png)

**Comment by kristijanhusak** [comment]
You cannot keep connection open with dadbod. Each query is a separate call.

**Comment by tin-pham** [comment]
> You cannot keep connection open with dadbod. Each query is a separate call.

Oke, thanks
