### ISSUE TITLE
Redshift can connect but tables are not visible

### ISSUE THREAD

**Issue by agalea91** [kristijanhusak/vim-dadbod-ui#124]
I was able to connect to Amazon Redshift using a DB URL like `postgres://...`

I can see my DB's schemas and I can run SQL! However I can't see any tables below the schemas in the explorer window. It's showing zero, e.g. `public (0)`

Do you know if there's a way I can get the explorer working for Redshift? Would be keen to test out some ideas. Thanks.

**Comment by SergioShz** [comment]
Hi,

I had the same problem some time ago, in my case (and maybe yours) the query that gets the table schema/name has an UNION to get also the materialised views from this table `pg_matviews` which exists in pg but not in redshift (making the query fail and not return data), deleting the second query after the UNION worked for me (quick and dirty I know) this is my diff with master:

```
diff --git a/autoload/db_ui/schemas.vim b/autoload/db_ui/schemas.vim
index 0f7b7af..e0cd99e 100644
--- a/autoload/db_ui/schemas.vim
+++ b/autoload/db_ui/schemas.vim
@@ -32,8 +32,7 @@ let s:postgres_list_schema_query = "

 let s:postgresql_args = '-A -c "%s"'
 let s:postgres_tables_and_views = "
-      \ SELECT table_schema, table_name FROM information_schema.tables UNION ALL
-      \ select schemaname, matviewname from pg_matviews;"
+      \ SELECT table_schema, table_name FROM information_schema.tables ;"
 let s:postgresql = {
       \ 'args': s:postgresql_args,
       \ 'foreign_key_query': printf(s:postgresql_args, s:postgres_foreign_key_query),
```

Of course would be nice a better solution, maybe a new connector for redshift for this kind of small differences but as I guess not so many people uses vim + redshift I've been using the quick solution for a while 😄 

Hope this helps!

**Comment by kristijanhusak** [comment]
Is there a way to detect if it's a redshift db? Modifying code directly is not really an elegant solution. If we can detect it somehow, we could include views only if it's not a redshift.

**Comment by agalea91** [comment]
You could detect it by running a query, something like `select version() like '%Redshift%'` - which would return true for redshift and false for postgres.

**Comment by jtw023** [comment]
Solution worked for me as well. Thank you @SergioShz! Another thing, do you know how I might see columns in my table here(see pic) instead of a few different queries where I can find that information?

<img width="1792" alt="Screenshot 2023-02-21 at 1 05 24 PM" src="https://user-images.githubusercontent.com/59935328/220460540-09b80efe-76c9-4c67-b8c1-153b727a898f.png">
