### ISSUE TITLE
Disable signcolumn on drawer

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#128]
Hi,

using https://github.com/przepompownia/vim-arctgx/blob/master/lua/arctgx/lineHover.lua (see also https://github.com/rcarriga/nvim-dap-ui/issues/92) I noticed that the drawer has not disabled signcolumn. This column seems to be not needed there even if the user has enabled it in init files.

For example with neovim please put `set signcolumn=auto:2-4` in init.vim and open the drawer.

**Comment by przepompownia** [comment]
Probably `auto` would be better than forcing to `no`.

**Comment by kristijanhusak** [comment]
`auto` is the default, from what I see in the [docs](https://neovim.io/doc/user/options.html#'signcolumn'). I'm ok with forcing it to `no`, but you could also achieve that fairly easily with `autocmd FileType dbui setlocal signcolumn=no`.

**Comment by kristijanhusak** [comment]
I'm perfectly fine setting it to `no`, I just wanted to hear your reasons for `auto`.

**Comment by przepompownia** [comment]
I'm not strongly convinced to `auto`. If I'm correct, `auto` gives the user a choice to put some custom signs. By default no signs will be displayed (like for `no`). Also in this case, the user can pus similar autocommand to force displaying signcolumn (if it makes any sense).

**Comment by kristijanhusak** [comment]
You're right. `no` it is.
Thanks.

**Comment by przepompownia** [comment]
Thank you too :+1:
