### ISSUE TITLE
:DBUI without any connections configured gets an error

### ISSUE THREAD

**Issue by johnnypea** [kristijanhusak/vim-dadbod-ui#13]
Any idea why I get this error when opening without any connections configured:
```
Error detected while processing function db_ui#open:                                                                                                
line    2:                                                                                                                                          
E117: Unknown function: open                                                                                                                        
E15: Invalid expression: s:dbui_instance.open()
```

It worked for me before.

**Comment by kristijanhusak** [comment]
I'm not able to reproduce it. Do you have the latest version?
Where it happens, vim/neovim? Which version?

**Comment by kristijanhusak** [comment]
Do you have some configuration in your init.vim for vim-dadbod-ui?

**Comment by johnnypea** [comment]
No, I'm trying to debug it with very basic config:
```
" Plugins {{{
" Begin vim plug
call plug#begin(expand('~/.config/nvim/plugged'))

" Tools {{{
Plug 'kristijanhusak/vim-dadbod-ui'  | " DB UI support
Plug 'tpope/vim-dadbod'              | " DB support
" }}}

" End the plugin registration
call plug#end()
" }}}
```

**Comment by kristijanhusak** [comment]
I've no idea what could be wrong. Just tested it on stable NVIM 0.4.3, works fine:

![screenshot](https://i.imgur.com/7oQDvlf.png)

open up file `~/.config/nvim/plugged/vim-dadbod-ui/autoload/db_ui.vim` and add this on 5th line (first line of the function):

```vimL
echom string(s:dbui_instance)
```

Give it a test, and give me output you got in cmd line.

**Comment by johnnypea** [comment]
```
{}   
Error detected while processing function db_ui#open[6]..1[11]..3[5]..10:
line   11:
E474: Attempt to decode a blank string
E474: Failed to parse 
Press ENTER or type command to continue
```

**Comment by kristijanhusak** [comment]
Ok i think your connections file is corrupted.
try deleting ~/.local/share/db_ui/connections.json and then try again.

**Comment by johnnypea** [comment]
That worked! Thank you for helping me out with this. Much appreciated.

Don't know how that happened.

**Comment by kristijanhusak** [comment]
I'll make sure that corrupted files are properly handled. Thanks for reporting.
