### ISSUE TITLE
Weird success popup

### ISSUE THREAD

**Issue by timsofteng** [kristijanhusak/vim-dadbod-ui#130]
Hello. I get weird success popup in my gruvboxy neovim:

![image](https://user-images.githubusercontent.com/51912173/166517971-5d9acd90-1560-415d-95f7-6d8677707979.png)

**Comment by kristijanhusak** [comment]
You get it out of nowhere or you are referring to it's readability?

**Comment by timsofteng** [comment]
> You get it out of nowhere or you are referring to it's readability?

Sorry for unclear description.
I mean poor readability and inconsistency with my color scheme.

**Comment by kristijanhusak** [comment]
You can override the colors by setting this hl groups:

```
NotificationInfo 
NotificationError
NotificationWarning
```
