### ISSUE TITLE
Possible to View Tables?

### ISSUE THREAD

**Issue by jtw023** [kristijanhusak/vim-dadbod-ui#131]
Hi, I have a problem likely from my own error(will attach a screenshot below).

Under `Schemas` on the left side everything shows (0) next to it. Should I be able to see all tables and what's in those tables? I can access everything when querying so it knows what's there, just doesn't show up on the gui.

![2022-05-04_12-00](https://user-images.githubusercontent.com/59935328/166807990-87e3ab79-1cb6-46d6-9cd9-663c333b4760.png)

**Comment by jtw023** [comment]
UPDATE: Initiating a new query and running `show search_path` returns $user, then one of my schemas. Strangely, I can't even see the tables inside that one schema. Continuing debugging.

**Comment by jtw023** [comment]
I haven't been able to get the schema browser working but [vim-dadbod-completion](https://github.com/kristijanhusak/vim-dadbod-completion) is able to view everything, solves the same problem. I think I like the completion element better anyways lol. Should I close this issue or is it something you'd like to leave open to continue working on?

As a side note, thank you for these plugins! Working with sql straight from neovim makes me a happy guy! I love it. :)

**Comment by kristijanhusak** [comment]
I think this is permission related issue. Can you tell me what you get from these 2 queries:

This one should return the schemes
```sql
    SELECT nspname as schema_name
    FROM pg_catalog.pg_namespace
    WHERE nspname !~ '^pg_temp_'
       and pg_catalog.has_schema_privilege(current_user, nspname, 'USAGE')
    order by nspname"
```

This one should return all tables from all schemas, but it seems it's not returning it for you
```sql
SELECT table_schema, table_name FROM information_schema.tables
```

**Comment by jtw023** [comment]
Interesting, those queries are both returning all tables and all schemas. I gave my connection the same name as one of my schemas though. Could that be causing the issue?

One other theory I have is that I'm using a PostgreSQL URL to connect to Amazon Redshift, since Redshift isn't officially supported. Maybe something is slightly off?

**Comment by gerrard00** [comment]
I'm seeing the same behavior connecting to local postgres containers. I also get proper autocompletion from "[vim-dadbod-completion](https://github.com/kristijanhusak/vim-dadbod-completion)".

**Comment by jtw023** [comment]
For anyone who comes across this, there is a temp fix on [issue 124.](https://github.com/kristijanhusak/vim-dadbod-ui/issues/124). It's not ideal but this solves the problem until a current fix can be made. :)
