### ISSUE TITLE
Mongodb queries are treated as sql queries

### ISSUE THREAD

**Issue by AshMagill** [kristijanhusak/vim-dadbod-ui#132]
When I go into new query with a mongodb url and start typing a query out, all of my autocompletion is suggesting that vim is treating the file as sql (and not js), is it possible to set it with a js file extension?

Thanks

**Comment by AshMagill** [comment]
Just for a bit of context:

![pic-full-220605-1917-50](https://user-images.githubusercontent.com/70498054/172040050-8d4afa68-8076-4da9-9ebb-ea9db84d17fc.png)

I changed the output in vim-dadbod to text (because it shows linting errors if the extension is json or js), and I was hoping I could change the input extension also (to js), but it didnt seem to do much..

```
**.vim/plugged/vim-dadbod/autoload/db/adapter/mongodb.vim**

function! db#adapter#mongodb#input_extension() abort
  return 'js'
endfunction

function! db#adapter#mongodb#output_extension() abort
  return 'txt'
endfunction
```

**Comment by kristijanhusak** [comment]
There is no mongodb support, at least I didn't work on any support for it, not sure if it works out of the box or not. 
I'm open to PRs, since I'm not a mongodb user.

**Comment by AshMagill** [comment]
Oh ok, thanks alot for the response, maybe this belongs in feature request and not issues, in the meantime I'll see if I can get someone to help me and I'll report back with a pull request if I get it sorted. thanks again
