### ISSUE TITLE
How can I connect to my SQL server?

### ISSUE THREAD

**Issue by thanh-doan-cko** [kristijanhusak/vim-dadbod-ui#134]
hi,

I tried to use my sql connection string such as

`let g:dbs = {
\ 'localSql': 'Server=localhost,1434;database=ADMINISTRATION;uid=sa;pwd=1234'
\ }
`

But it does not work.

Can you support me?

Cheers

**Comment by kristijanhusak** [comment]
What kind of database are you trying to add? You can see what is supported in dadbod via `:help dadbod-urls`

**Comment by thanh-doan-cko** [comment]
Thank you. I can manage to add the connection.
