### ISSUE TITLE
Transpose output table

### ISSUE THREAD

**Issue by antosha417** [kristijanhusak/vim-dadbod-ui#136]
Hi! I'm very exited about this plugin and enjoy using it!

Is it possible to transpose the table in the output window? 
Some of tables that I query have **a lot** of columns and it would be so much easier to scoll results from up to bottom, not from left to right. 

I want the output to be something like this:
```
+-------+--------+--------+--------+
| id    | 1      | 2      | 3      |
+-------+--------+--------+--------+
| value | value1 | value2 | value3 |
+-------+--------+--------+--------+
...
```
Where `id` and `value` are column names. And the rest are values

**Comment by kristijanhusak** [comment]
I'm not sure which db are you using, but if you are using Postgres, you can use extended display view. It was broken, but I just pushed a fix. In the output window, press `<Leader>R` to switch to extended display. It's not exactly how you want it, but it shows column per each line.

**Comment by antosha417** [comment]
Right now mostly I use mysql, I see that the feature must work there.
You are right, that's not exactly what I had in mind, but it is still very good and saves me from horizontal scrolling!

The only thing that bothers me is after update I have this error message on every search
![Screen Shot 2022-06-20 at 16 27 36](https://user-images.githubusercontent.com/14187674/174612359-263a491c-d5ab-467e-96b3-3d2869e303be.png)

**Comment by kristijanhusak** [comment]
I just pushed an update that should fix that.

**Comment by antosha417** [comment]
Thank you a lot for your help. You are super fast to respond
