### ISSUE TITLE
Async result

### ISSUE THREAD

**Issue by marcelofern** [kristijanhusak/vim-dadbod-ui#145]
Hi there!

Is there any plan to make the fetching of results asynchronously?
It would be great so that we can still use vim while the results are being fetched, specially for slow queries.

TA!

**Comment by kristijanhusak** [comment]
There was async support but recently it was reverted because of some issues. There's a pending PR with the fix https://github.com/tpope/vim-dadbod/pull/117. Until then you can use branch from my fork https://github.com/kristijanhusak/vim-dadbod/tree/async-support
