### ISSUE TITLE
E171: Missing :endif - Unable to execute query

### ISSUE THREAD

**Issue by sabah1994** [kristijanhusak/vim-dadbod-ui#151]
Hi, please have a look at the screenshot. This occurs when I try to write the buffer in order to execute the query.

![Screenshot 2022-12-08 at 11 23 47](https://user-images.githubusercontent.com/73726199/206434829-a2e39441-b9c9-473a-ac30-e1b29ce4c88a.png)

**Comment by kristijanhusak** [comment]
I would suggest to switch to my fork of vim-dadbod temporarily https://github.com/kristijanhusak/vim-dadbod/tree/async-support

**Comment by kristijanhusak** [comment]
This issue should be fixed now.
