### ISSUE TITLE
MSSQL password prompt

### ISSUE THREAD

**Issue by ckangnz** [kristijanhusak/vim-dadbod-ui#155]
So i have a sql server running in a docker container at port :14333.

I used the connection query : `jdbc:sqlserver://localhost:14333;databaseName=default;username=sa;password=password;`

But I think the sqlcmd has an update where it doesn't allow you to put in the password in the connection string, but it actually prompts you or wants you to save it as a global variable.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/17423698/214995317-6fa1bb06-eb71-4e83-95bb-b29dccb7ea0e.png">

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/17423698/214995497-6b5e2cf2-e1c9-41c0-acfa-acc0cce516df.png">

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/17423698/214995531-be4f9e51-9525-4b6e-bb6f-397cfbc89ddb.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/17423698/214995556-9194b821-8434-4923-9add-80c4923c939f.png">

Can this plugin ask for password ?

**Comment by ckangnz** [comment]
Any update on this?

**Comment by ckangnz** [comment]
Sorry for the late response;

The error actually comes from `:DB`. I should have raised the issue in `tpope/vim-dadbod`.

**Comment by ckangnz** [comment]
I raised an issue in that repo instead.
https://github.com/tpope/vim-dadbod/issues/127

But once this is implemented, i think the UI will require similar update to prompt the user to type in the password?

**Comment by kristijanhusak** [comment]
Maybe, I'm not sure. `vim-dadbod` knows how to ask for password, at least for MySQL. I'm not sure about MSSQL.

**Comment by ckangnz** [comment]
I guess you can close this one s it is going to be fixed in the other repo
