### ISSUE TITLE
Show line numbers on sidebar 

### ISSUE THREAD

**Issue by xbladesub** [kristijanhusak/vim-dadbod-ui#158]
How to show (relative) line numbers on the sidebar?

**Comment by kristijanhusak** [comment]
This should work:
```vimL
autocmd FileType dbui setlocal number relativenumber
```

**Comment by nikinbaidar** [comment]
> ```viml
> autocmd FileType dbui setlocal number relativenumber
> ```

Actually it doesn't. I am on neovim and there isn't any relative numbers or even number for that matter on the dbui filetype unless I explicitly run them on every session. I've numbers enabled in every  other buffer. 

I have tried adding "set nu rnu"  to ftplug/dbui as well as from an autocmd like you suggested.

**Comment by kristijanhusak** [comment]
You're right. There's a custom autocmd being fired, that should be used instead.

```vim
autocmd User DBUIOpened setlocal number relativenumber
```
