### ISSUE TITLE
 Can't open file connections.json for writing: no such file or directory 

### ISSUE THREAD

**Issue by naknode** [kristijanhusak/vim-dadbod-ui#16]
When I try to add a new DB connection (pg), I get: ` Can't open file /Users/dan/.local/share/db_ui/connections.json for writing: no such file or directory `

This happens with any string I give it. Any ideas?

nvim 0.4.3
macOSX Catalina 10.15.4

**Comment by kristijanhusak** [comment]
Yeah I wasn't making sure directory for connections exists. Should be ok now.

**Comment by naknode** [comment]
Thank you. That was quick.
