### ISSUE TITLE
Exit gracefully

### ISSUE THREAD

**Issue by naknode** [kristijanhusak/vim-dadbod-ui#18]
Is there a keymap where, after you're done using the DBUI... you want to leave the query results, toggle (presumedly) the drawer closed and delete the query buffer so you're back to the file you were previously at?

 I mean I could automate a script to do this but perhaps this can be a nice default?

**Comment by kristijanhusak** [comment]
I guess we could have an option for that. Did you try to do it youself, do you have something already for it?

**Comment by kristijanhusak** [comment]
In this situation, I think the simplest thing to do would be to open up a new tab. Once you're finished, just close the tab and you're good to go.

**Comment by naknode** [comment]
True. A simple vim keybind and you'd be good to go.

**Comment by kristijanhusak** [comment]
@naknode I added support for `<mods>` (`:help <mods>`), which means that you can open up dbui in new tab like this:
```
:tab DBUI
```
Hope this helps.
