### ISSUE TITLE
mssql varchar(512) occupies 512 characters when its unnecessary

### ISSUE THREAD

**Issue by KenroLe** [kristijanhusak/vim-dadbod-ui#181]
Hey,

Ive been having issues when using mssql where a varchar(512) is 512 characters wide in dbout despite the actual resulting data in the column being at most 30 characters.
Im using mssql and looking for atleast a hack to deal with this.

Would appreciate any help I can find, thanks!

**Comment by kristijanhusak** [comment]
Output is not controlled by this plugin. For mssql, `sqlplus` is in charge of controlling the output. There are maybe ways to configure it. See https://github.com/kristijanhusak/vim-dadbod-ui/issues/120.
