### ISSUE TITLE
When I press `o` at a node, it requires me to hit `<Enter>` to continue

### ISSUE THREAD

**Issue by LintaoAmons** [kristijanhusak/vim-dadbod-ui#182]
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/95092244/736ae236-fa65-4a86-9352-4478b40fb6bb)

**Comment by kristijanhusak** [comment]
You are maybe getting some errors. Once you press enter, do `:messages` to see if you get anything in the output.

**Comment by LintaoAmons** [comment]
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/95092244/a9725427-6c51-4b8b-8b7a-7aa9255d7e99)

That's all it says...

I also suspect that, but don't know how to find out the error msg

**Comment by LintaoAmons** [comment]
![show](https://github.com/kristijanhusak/vim-dadbod-ui/assets/95092244/b740d290-bfca-4fe8-9e51-a72bdfdbda4c)

**Comment by kristijanhusak** [comment]
Ok I just noticed that you are using `cmdheight=0`. DBUI echoes some messages that cause the prompt.
See if you have `db_ui_force_echo_notifications = 0` in your config, and remove it. It should show messages in the popup window.
Other solution is to use `cmdheight=1`.

**Comment by LintaoAmons** [comment]
Thx!! for making this nice plugin~~
to use nvim as some kind of frontend~
Like TUI, `k9s`, `lazygit` etc.
