### ISSUE TITLE
Column names in query result becomes misaligned when containing åäö

### ISSUE THREAD

**Issue by mrDoktar** [kristijanhusak/vim-dadbod-ui#183]
Hi.

I'm connecting to a Microsoft SQL Server and running
`select top 200 * from [Anställda];`

Some of the columns in table `Anställda` (Employees in Swedish) have Swedish characters in them (å ä ö). The column names gets cropped 1 char for each instance of å, ä, or ö in the name.

Example of what I get in the query result view:
```
Anställningsnumme       Personligt_lönefält    Personligt_lönefält    Personligt_lönefält    
------------------------ ------------------------ ------------------------ ------------------------
```
What I'm expecting:
```
Anställningsnummer       Personligt_lönefält_1    Personligt_lönefält_2    Personligt_lönefält_3
------------------------ ------------------------ ------------------------ ------------------------
```

**Comment by kristijanhusak** [comment]
This plugin does not control the output of the query. It comes from `sqlplus` in the case of SQL server. 
Try setting one of these in the output window to see if it helps, but I don't think I will: https://stackoverflow.com/a/73575838
