### ISSUE TITLE
Incorrect url parsing for special characters in password

### ISSUE THREAD

**Issue by SpicyChickenFLY** [kristijanhusak/vim-dadbod-ui#186]
would parse url incorrectly if there are some special characters like @, # inside the dsn components (mostly inside password).
e.g.  use config:
[{ "name": "test", "url": "mysql://user:p@ssword@localhost:5432" }]
get error:
Error connection to db test: DB exec error: 2005 (HY000): Unknown server host 'ssword@localhost:5432' (-2)

**Comment by kristijanhusak** [comment]
Do you have this issue when using only `vim-dadbod` ?

**Comment by skbolton** [comment]
you have to escape the @ since it has meaning in the url %40
