### ISSUE TITLE
Line wrapping issue - Query result

### ISSUE THREAD

**Issue by hhertout** [kristijanhusak/vim-dadbod-ui#188]
Hello, thank's for your work !

I have some issue with the result of the query... all works fine exept this :

![Capture d’écran 2023-09-03 à 01 04 17](https://github.com/kristijanhusak/vim-dadbod-ui/assets/109511726/8ea9286f-a80c-4033-9a8d-cbf09f6f2480)

I think it's cause to line wrapping but i don't know how to solve the problem... i try with nvim config to force line wrap, but no result atm.

I don't have the problem with dad-bod, just with dadbod-ui.

Thank's for your help.

**Comment by kristijanhusak** [comment]
By "line wrapping" do you mean folding?

**Comment by hhertout** [comment]
Yes... sorry

**Comment by kristijanhusak** [comment]
This should work

https://github.com/kristijanhusak/vim-dadbod-ui/issues/107#issuecomment-907341998

**Comment by hhertout** [comment]
It's exactly what i search ! Thank's !!
