### ISSUE TITLE
UI Only works after connect with db with dadbod

### ISSUE THREAD

**Issue by DeodatoBastos** [kristijanhusak/vim-dadbod-ui#190]
I have to connect with my db first with raw dadbod to can you the ui.

The following error appears:

![error](https://github.com/kristijanhusak/vim-dadbod-ui/assets/82189095/96570b49-03bc-4ec6-9a4e-a9e996981ac5)

When I try again, this happes:

![error2](https://github.com/kristijanhusak/vim-dadbod-ui/assets/82189095/743eb7a2-374c-4c7d-8111-ec3de5d5ce8c)

The database password is "my_password".

Configuration with lazy:

```lua
{
        "tpope/vim-dadbod",
        cmd = "DB",
        opt = true,
        requires = {
            "kristijanhusak/vim-dadbod-ui",
            "kristijanhusak/vim-dadbod-completion",
        },
    },
    {
        "kristijanhusak/vim-dadbod-ui",
        cmd = require("settings.dbui").cmd,
        init = function()
            require("settings.dbui").init()
        end,
        dependecies = require("settings.dbui").dependencies,
    },
    {
        "kristijanhusak/vim-dadbod-completion",
        opt = true,
    },
```

the `dbui.lua` file:

```lua
return {
    cmd = {
        "DBUI",
        "DBUIToggle",
        "DBUIAddConnection",
        "DBUIFindBuffer",
        "DBUIRenameBuffer",
        "DBUILastQueryInfo",
        "DBUIHideNotifications"
    },
    init = function()
        vim.g.db_ui_show_help = 0
        vim.g.db_ui_win_position = 'right'
        vim.g.db_ui_use_nerd_fonts = 1

        vim.g.db_ui_save_location = '~/.local/share/db_ui'
        -- vim.g.db_ui_tmp_query_location = '~/code/queries'

        vim.g.db_ui_hide_schemas = { 'pg_toast_temp.*' }
    end,
    dependencies = {
        {
            'tpope/vim-dadbod',
            lazy = true
        },
        {
            'kristijanhusak/vim-dadbod-completion',
            ft = { 'sql', 'mysql', 'plsql' },
            lazy = true
        },
    },
}
```

**Comment by kristijanhusak** [comment]
This is definitely due to lazy configuration.
I'm not sure I understand what you posted. You have everything defined twice.
You can check how I set it up https://github.com/kristijanhusak/neovim-config/blob/master/nvim/lua/partials/plugins/db.lua#L1

**Comment by kristijanhusak** [comment]
I added an example with lazy.nvim in the docs https://github.com/kristijanhusak/vim-dadbod-ui#installation. Let me know if it works out.

**Comment by DeodatoBastos** [comment]
That doesn't work for me.

I will try to explain better:

When I try to run `:DBUIToggle` for the first time without run `:DB` these errors appears:

![dbui_error_first](https://github.com/kristijanhusak/vim-dadbod-ui/assets/82189095/48e21e1e-8de0-429d-a6dc-f102600fac0e)

When I try to run `:DBUIToggle` for the second time:

![dbui_error_second](https://github.com/kristijanhusak/vim-dadbod-ui/assets/82189095/92323f6a-8b2d-47ed-958e-8bba9a17d4e0)

For the third(+) time:

![dbui_error_third](https://github.com/kristijanhusak/vim-dadbod-ui/assets/82189095/5e2832bd-80b5-46e9-8131-fe2a0703709d)

The same happens when I use `:DBUI`, but the function is *open* instead of *toggle*.
After use `:DBUI` or `:DBUIToggle` for the second time, I cannot use I it at all without restart Neovim.

If I run `:DB` after the first time or before `:DBUI` or `:DBUIToggle` everything works well.

**Comment by kristijanhusak** [comment]
This is a configuration issue. I checked your dotfiles.
Try removing this section https://github.com/DeodatoBastos/nvim-setup/blob/main/lua/plugins.lua#L231-L239 and this section https://github.com/DeodatoBastos/nvim-setup/blob/main/lua/plugins.lua#L248-L251, do `:Lazy sync` and try again.

**Comment by DeodatoBastos** [comment]
That's works thanks!

I've already tried this, but isn't working.
I see now that there was a typo in my settings.

Thank you for the help!
Btw, incredible plugin!
