### ISSUE TITLE
Using nvim-notify

### ISSUE THREAD

**Issue by ZyriabDsgn** [kristijanhusak/vim-dadbod-ui#191]
Hi there, thanks for this great plugin :)
I was wondering if there was a way to pipe the notifications to [nvim-notify](https://github.com/rcarriga/nvim-notify) instead of using the plugin's default notifications UI?

Cheers

**Comment by kristijanhusak** [comment]
This is something I planned to add, So I'll consider this as enhancement issue.

**Comment by kristijanhusak** [comment]
This is now implemented. To use it add this to your configuration:
```vim
let g:db_ui_use_nvim_notify = 1
```

Note that it's using Neovim's `vim.notify` API, so in order to use `nvim-notify` plugin you need to assign it to `vim.notify` as they suggest in their docs

**Comment by ZyriabDsgn** [comment]
You da man

**Comment by andres-lowrie** [comment]
for future search engine travelers. 

As mentioned by `kristijanhusak`, assigning the plugin to `vim-notify` means putting this in your neovim config
 
```lua
vim.notify = require('notify')
```

Here's an example on how to do that if you're using [lazy](https://github.com/folke/lazy.nvim)


```lua
  {
    'rcarriga/nvim-notify',
    config = function()
      vim.notify = require('notify')
    end
  },
```
