### ISSUE TITLE
Press return after every cmd

### ISSUE THREAD

**Issue by chrstnwhlrt** [kristijanhusak/vim-dadbod-ui#192]
Hey there,
great work you did here!

I was just wondering - after using the default mappings in the dbui buffer I've to confirm the execution everytime with return. Is there something I'm missing in my configuration?

I can override all the default mappings with the same mappings adding a <CR> at the end but I've got the feeling there's a smarter way to fix it.

**Comment by kristijanhusak** [comment]
Hey! Check if you have the same issue as reported here https://github.com/kristijanhusak/vim-dadbod-ui/issues/182

**Comment by chrstnwhlrt** [comment]
cmdheight = 1 did the trick, thanks a lot!
