### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by chrstnwhlrt** [kristijanhusak/vim-dadbod-ui#194]
The notifications are quite verbose:

<img width="443" alt="image" src="https://github.com/kristijanhusak/vim-dadbod-ui/assets/866769/64ee7cf4-eff9-4af4-a044-b113e528e9d3">

Is there a way to disable them completly? Activating nvim-notify with the settings works, as I don't use nvim-notify - is there any other flag that does the trick?

**Comment by kristijanhusak** [comment]
You can force them to be echoed into the command line with this option: https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L703.

I can add an option for completely disable them, but I would not recommend doing that.

**Comment by chrstnwhlrt** [comment]
Great that's working for me! I was initially confused by this parameter as I thought it would echo in the way that it will print all notifications besides to the notification window also to the command line.

**Comment by justicenyaga** [comment]
> You can force them to be echoed into the command line with this option: https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L703.

I have tried to use this settings option, but it still bothers me since I'm using nvim-notify.

> I can add an option for completely disable them, but I would not recommend doing that.

This would be the ideal way to deal with this as I prefer not having these notifications.

**Comment by jumski** [comment]
i second @justicenyaga - i think i will totally manage it disabled

**Comment by kristijanhusak** [comment]
I added an option to silence "info" notifications in c0e33f0bb2ea. Just set `let g:db_ui_disable_info_notifications = 1` to your config.
Note that warnings and errors are still shown, but those should not happen in normal usage.
