### ISSUE TITLE
Replace binary values in output

### ISSUE THREAD

**Issue by shaunmolloy** [kristijanhusak/vim-dadbod-ui#200]
Binary column values appear corrupt in the output.

How about replacing those values in the output with an empty value,
to clean up the view?

<img width=500 src=https://github.com/kristijanhusak/vim-dadbod-ui/assets/8168925/bc8de86f-4745-4f80-946d-c01251420ae8>

**Comment by kristijanhusak** [comment]
Output is controlled by cli used behind the scenes, which is `mysql` here. You can try to convert it to hex with this https://stackoverflow.com/a/46418613, but I didn't test it.

**Comment by shaunmolloy** [comment]
Thanks @kristijanhusak for the fast reply. That solves the issue :+1: 
I'll close this.

Added the following to `/etc/my.cnf`:

```conf
[mysql]
binary-as-hex = true
```
