### ISSUE TITLE
enhancement: pagination

### ISSUE THREAD

**Issue by MattiasMTS** [kristijanhusak/vim-dadbod-ui#201]
Hi @kristijanhusak!

Just want to say, I fricking love this plugin - definitely enhanced my developer workflow. I was wondering about two things:

1. `dbout` pagination
2. lua fork

Essentially, do you think it is possible to add a pagination style to the dbout? It is always frustrating when you query something "super large" and the `dbout` basically freezes the screen hehe. Similarly to [nvim-dbee](https://github.com/kndndrj/nvim-dbee/) it would be cool if, on `dbout`, one could toggle "left/right" on "H/L" keymaps, where each pagination would toggle e.g. 100 rows at a time. What do you think?

Secondly, do you think it is worth extending/re-writing this plugin in lua? Just wondering what's your view is on this :>

Again, thanks!

**Comment by kristijanhusak** [comment]
> Essentially, do you think it is possible to add a pagination style to the dbout? It is always frustrating when you query something "super large" and the dbout basically freezes the screen hehe. Similarly to [nvim-dbee](https://github.com/kndndrj/nvim-dbee/) it would be cool if, on dbout, one could toggle "left/right" on "H/L" keymaps, where each pagination would toggle e.g. 100 rows at a time. What do you think?

The output of the query is handled by the underlying CLI tool (psql, mysql, etc.) via vim-dadbod. The plugin you linked seems to have its own backend so it's able to handle that. That is out of scope for this plugin.

> Secondly, do you think it is worth extending/re-writing this plugin in lua?

I was thinking about this but it would cause incompatibility with Vim. Since vim-dadbod supports both Vim and Neovim, I'm also planning to support both for the time being.

**Comment by MattiasMTS** [comment]
> That is out of scope for this plugin. 

> Since vim-dadbod supports both Vim and Neovim

Alright, that makes sense 😄 Thanks for giving your thoughts on this @kristijanhusak  with such short notice. I hope you have an amazing day! Closing this issue now. 💚
