### ISSUE TITLE
Table Structure not showing properly.

### ISSUE THREAD

**Issue by sakithajayasinghe** [kristijanhusak/vim-dadbod-ui#208]
![Screenshot from 2023-11-22 20-09-31](https://github.com/kristijanhusak/vim-dadbod-ui/assets/125004069/64ce87a9-285c-419b-bf35-79a48c41b527)

Table structure is showing single one line.please help
NVIM = 0.9.4

**Comment by sakithajayasinghe** [comment]
select query.then,press:,then w

**Comment by kristijanhusak** [comment]
It's folded. You can disable local folding with this autocmd:

```vim
autocmd FileType dbout setlocal nofoldenable
```
