### ISSUE TITLE
DBUI stop working when given a wrong connection

### ISSUE THREAD

**Issue by Jlchong3** [kristijanhusak/vim-dadbod-ui#219]
Honestly, I am kind of new in this, so I am searching for help, I am having a similar issue to #190 where the cmd commands like DBUIToggle won't work.

They worked before without an issue, but when I failed to do a connection it stopped working, I tried reinstalling the whole thing but the problem persists. If someone could point out the problem or knows what is the solution pls let me know  

My config for dadbod
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/127264125/bb0feae5-3919-47be-86b3-7b9a9a6485cf)

First time trying to execute DBUIToggle
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/127264125/1e0656dd-e2e1-4b63-b656-973bc3d3db05)

Second time
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/127264125/abf9e869-586f-4cbd-8c45-c1eb0dee8ed1)

The issue I am referencing seemed to have problems in the overall config so I will have my config open in case someone is willing to help

**Comment by Jlchong3** [comment]
> They worked before without an issue, but when I failed to do a connection it stopped working, I tried reinstalling the whole thing but the problem persists. If someone could point out the problem or knows what is the solution pls let me know

Apparently, it had more to do with this than with the configuration, I manually deleted all the connections from the connections.json, and it worked again. Don't know the reason though, so I am leaving this here in case this is a bug worth fixing.

**Comment by kristijanhusak** [comment]
Closing this for now. If it happens again, please open up a separate issue.
