### ISSUE TITLE
Table format off when text field includes line breaks

### ISSUE THREAD

**Issue by AdamWorthington** [kristijanhusak/vim-dadbod-ui#221]
![Screen Shot 2024-02-09 at 1 39 03 PM](https://github.com/kristijanhusak/vim-dadbod-ui/assets/5733807/b025e463-42b5-428a-b901-9e38f81ec4be)
As seen from the screenshot, when a field contains line breaks any query result will have bugged formatting.

**Comment by kristijanhusak** [comment]
Output is not controlled by any of the plugins, either this one or vim-dadbod. It is the raw output of the CLI that is used behind the scenes.
