### ISSUE TITLE
bind parameter delimiter config 

### ISSUE THREAD

**Issue by greg-nagy** [kristijanhusak/vim-dadbod-ui#228]
I am using node-pg which support parametrized queries like this `SELECT * FROM location WHERE name = $1` and then passing in an array for the parameters as a 2nd argument for the query function. 

If I could change the delimiter from `:` to `$` it would mean that I can freely move sql queries between my code and dadbod ui.

I couldn't find anything related to this after quickly glancing through the docs. 
Is it something that's possible? If not I am happy to try and make the change.

**Comment by kristijanhusak** [comment]
This is now added. You can switch to that format like this:
```vim
```

**Comment by greg-nagy** [comment]
thanks a lot 

this is such an amazing quality of life change for me :)

**Comment by jonathanmorris180** [comment]
Hi @kristijanhusak, this doesn't seem to work in Neovim. I tried adding this: `vim.g.db_ui_bind_param_pattern = [[\$\d\+]]` to my config, but when I run the command, I get `No bind parameters to edit`. Any ideas why this might be happening?

**Comment by jonathanmorris180** [comment]
@kristijanhusak That works, thanks! I thought I'd be able to edit the params before executing, but this makes sense.
