### ISSUE TITLE
Undefined variable: expanded

### ISSUE THREAD

**Issue by acamso** [kristijanhusak/vim-dadbod-ui#23]
NVIM v0.3.8, MongoDB v3.6.8

When attempting to open a "table" in the drawer using "o", I'm receiving:

> Error detected while processing function <SNR>158_method[2]..54:                                                                                                        
> line   21:
> E121: Undefined variable: expanded
> E15: Invalid expression: !tree.expanded

All tables are listed fine, and I receive results when running `:DB db.xxx.find()`

**Comment by kristijanhusak** [comment]
Do you know if it happens only for mongo? Are you able to test some other db?

**Comment by kristijanhusak** [comment]
I pushed a change. Can you update and give it another test?

**Comment by acamso** [comment]
> Do you know if it happens only for mongo? Are you able to test some other db?

I haven't tried another db, but I can if needed.

> I pushed a change. Can you update and give it another test?

For the tree I am receiving `~ List`. It opens the query fine, but it is incorrect: `db.db.project.find()` but should be `db.project.find()`.

**Comment by kristijanhusak** [comment]
I fixed it to be `db.project.find()`. Yeah, that's the only table helper available for mongo. I'm not working so much with mongo so I haven't added it myself. If you think there could be some useful defaults let me know what they are.

**Comment by acamso** [comment]
> I fixed it to be `db.project.find()`. Yeah, that's the only table helper available for mongo. I'm not working so much with mongo so I haven't added it myself. If you think there could be some useful defaults let me know what they are.

Thanks, looks great. I'll come up with a list as I go along.

**Comment by kristijanhusak** [comment]
Ok. Open up a PR if you figure out some. Closing this since it's fixed.
