### ISSUE TITLE
JOIN not working with SQL Server

### ISSUE THREAD

**Issue by Maduki-tech** [kristijanhusak/vim-dadbod-ui#236]
Hello,
I'm trying out this Plugin, I can not make the  JOIN work with an SQL Server connection (Don't know if it working with another connection)

> Information I'm new to SQL in general

So I try to learn SQL now and I expect that this code is working: 

![Screenshot 2024-05-18 at 21 17 15](https://github.com/kristijanhusak/vim-dadbod-ui/assets/70664223/ad9f3431-cb88-42a2-997b-2f7fa2bb02f7)

In my understanding, I expect that the table also shows the posts.

When I run the same query on the same DB via Table Plus ( MacOS DB Tool ) I get the correct response
![Screenshot 2024-05-18 at 21 18 48](https://github.com/kristijanhusak/vim-dadbod-ui/assets/70664223/75db8dbf-4ebb-4da0-aa73-cee4855cefd4)

> I use Nvim 0.10, No modification to the Plugin or to `vim-dadbod`.

**Comment by dbmatheus** [comment]
Hi @Maduki-tech, I think that you're not scrolling to the right to see the other columns. It's just formatting. I'm not sure in SQL Server but prior to the query you usually format the output limiting the number of characters.

**Comment by Maduki-tech** [comment]
Oh yes you are right! Thx @dbmatheus
