### ISSUE TITLE
Error connecting to db local:DB:'mysql'executable not found

### ISSUE THREAD

**Issue by hyawara** [kristijanhusak/vim-dadbod-ui#243]
![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/31959238/0c5abdad-888a-4934-9ae2-4f09017178d1)

config :

![image](https://github.com/kristijanhusak/vim-dadbod-ui/assets/31959238/ac520fe4-a9d4-4bbb-9904-4f34762c7636)

**Comment by kristijanhusak** [comment]
You need to install mysql on your machine to get `mysql` executable.

**Comment by hyawara** [comment]
My mysql is installed using docker, can I use mysql executable? 
If not, how to install mysql executable using scoop under windows

> You need to install mysql on your machine to get `mysql` executable.

**Comment by hyawara** [comment]
> I'm not a Windows user, but probably something like this https://gist.github.com/ergin/b90ebee3cf32161ead257edda4f0d2ff

I will give it a try and thank you very much
