### ISSUE TITLE
QUESTION: How do you view/use a schema other than public?

### ISSUE THREAD

**Issue by tandrewnichols** [kristijanhusak/vim-dadbod-ui#25]
I guess I would've expected the flow, when you run `:DBUI` to be

```
- dbs
  - schemas
    -tables
```

That is, when you open a database, you'd get a list of schemas, but instead you just get tables in the public schema. I don't see anything in help about navigating schemas. Is that just not supported?

**Comment by kristijanhusak** [comment]
I'm using what's available as part of dadbod. Schemas are not supported. I'll maybe add them myself at some point.

**Comment by tandrewnichols** [comment]
Wasn't aware of that, thanks for the info.

**Comment by kristijanhusak** [comment]
I added support for schemas for mysql, postgres and sqlserver.

**Comment by tandrewnichols** [comment]
Dang, nice work!
