### ISSUE TITLE
display NULL and empty string

### ISSUE THREAD

**Issue by letieu** [kristijanhusak/vim-dadbod-ui#255]
Currently NULL and empty string look the same on dbout. Can we have some way to format ?

**Comment by kristijanhusak** [comment]
Which db? In postgres you can create global `.psqlrc` file that will hold some configuration to show this.

https://database.guide/how-to-show-null-values-when-running-queries-in-psql-postgresql/

**Comment by letieu** [comment]
> Which db? In postgres you can create global `.psqlrc` file that will hold some configuration to show this.
> 
> https://database.guide/how-to-show-null-values-when-running-queries-in-psql-postgresql/

very appreciated
