### ISSUE TITLE
Dont execute on save

### ISSUE THREAD

**Issue by appleseedexm** [kristijanhusak/vim-dadbod-ui#259]
I would like to have a flag to disable execute on save. Personally I think this is something very dangerous and I prefer a very distinctive action to execute a query against the database that's not read only. So far I use the `<leader>S` functionality and try not to save ever. 
BUT having a db buffer open in the background always puts you at danger when saving all buffers, which is something I do rather often when doing development work. 

Where this becomes a bit intense is with saved queries. Maybe this tool is not meant for this kind of work, but designing a query in a saved file means you just cant save your progress ever without running it against the db? Am I missing something? 

For me the best solution would be to "save" to never trigger execution.

**Comment by kristijanhusak** [comment]
https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L552

**Comment by appleseedexm** [comment]
Thanks, and sorry, completely missed that there's a doc.
