### ISSUE TITLE
[QUESTION]: Is MySQL config group suffixes supported via ENV?

### ISSUE THREAD

**Issue by dzintars** [kristijanhusak/vim-dadbod-ui#275]
Hi.
Just a question, does this plugin supports `mysql --defaults-group-suffix=_dev_dba` as an environment variable like `export DB_UI_DEV='mysql --defaults-group-suffix=_dev_dba'`?
DB config are configured within `~/.my.cnf` file with various DB connections.
I could reuse those. Not a big deal. Just curious.

Client config sample:
```ini
[client_dev_dba]
host=192.168.0.0
port=3306
user=secretdbauser
password=secretpass
```

In `mysql` CLI you use it via `mysql --defaults-group-suffix=_dev_dba < your-script.sql`

**Comment by kristijanhusak** [comment]
Hi, it's not possible to modify the executable and it's arugments like that.
You can pass some things through the connection string (see here https://github.com/tpope/vim-dadbod/blob/master/doc/dadbod.txt#L150), but that's about it.
