### ISSUE TITLE
Update default queries in other schemas to include the schema name

### ISSUE THREAD

**Issue by tandrewnichols** [kristijanhusak/vim-dadbod-ui#28]
I almost put this in #25, but I figured a new issue would help others looking for the same thing a little easier.

I just updated to the new version with schema support; it looks great. There is one issue (which is easy to work around so it's not an urgent thing), but the default queries (like LIST) need to be updated in schemas other than public to include the schema (i.e. `select * from schemaname.tablename limit 200`), otherwise (at least in postgres, which is what I'm using - not sure about other dbs) you get "relation does not exist" errors. It's easy to work around this by adding it manually however.

I might even try to tackle this a bit later. Seems like it would be pretty straight forward.

Thanks for the fast turnaround on #25!

**Comment by kristijanhusak** [comment]
I just fixed it. Do an update and give it a test. For public schema in postgres, it will not add it because it's not needed, but for other it will.

**Comment by tandrewnichols** [comment]
Yeah, it's working. Thanks!
