### ISSUE TITLE
No table schema?

### ISSUE THREAD

**Issue by foxale** [kristijanhusak/vim-dadbod-ui#29]
Hey,

First of all - Great job. That's exactly the kind of tool I was looking for. Unfortunately, after connecting to SQL Server db via jdbc, there is no schema prefix visible and therefore table names look duplicated when if fact they have the same name but different schemas. 

Due to some github bug I can't put image here, but I guess it's pretty straightforward to visualize the problem.

**Comment by kristijanhusak** [comment]
Hi,

I don't have much experience with SQL Server, but how can it happen that schema doesn't have prefix? I'm not sure what that exactly means. No need for screenshot, but try to write up some example with tree structure so I can better understand it.

**Comment by foxale** [comment]
So let's say I have two schemas _dbo_ and _tmp._, both have a table named _users_. 
So I imagine the tree should look like this: 

```
V DBname 
    > dbo.users
    > tmp.users
```

instead I see 

```
V DBname 
    > users
    > users
```

and if I "Open/Toggle selected item" on either, both show their contents, like this: 

```
V DBname 
    > users
         ~ List
    > users
         ~ List
```

**Comment by kristijanhusak** [comment]
Your tree should look like this:
```
V DBName
  V Schemas
    V dbo
      > Users
    V tmp
      > Users
```

Does your db url start with `sqlserver://` ?
Do you even have `Schemas` option?

**Comment by foxale** [comment]
It starts with `jdbc:sqlserver://` and there is no `Schemas` option.

**Comment by foxale** [comment]
Removing

**Comment by kristijanhusak** [comment]
I think using it without `jdbc:` at the start should fix the issue.
