### ISSUE TITLE
tables not sorted when rendering

### ISSUE THREAD

**Issue by gh-liu** [kristijanhusak/vim-dadbod-ui#290]
I have multiple tables with the same prefix and a timestamp suffix, they are not appear in the order.

**Comment by gh-liu** [comment]
Maybe we can sort the tables before rendering:

```diff
diff --git a/autoload/db_ui/drawer.vim b/autoload/db_ui/drawer.vim
index 7ccf620..7da7a81 100644
--- a/autoload/db_ui/drawer.vim
+++ b/autoload/db_ui/drawer.vim
@@ -462,7 +462,8 @@ function! s:drawer.render_tables(tables, db, path, level, schema) abort
   if !a:tables.expanded
     return
   endif
-  for table in a:tables.list
+  let tables_list = sort(a:tables.list)
+  for table in tables_list
     call self.add(table, 'toggle', a:path.'->'.table, self.get_toggle_icon('table', a:tables.items[table]), a:db.key_name, a:level, { 'expanded': a:tables.items[table].expanded })
     if a:tables.items[table].expanded
       for [helper_name, helper] in items(a:db.table_helpers)
```

**Comment by kristijanhusak** [comment]
We can do that, but through an option.

**Comment by gh-liu** [comment]
> We can do that, but through an option.

A sort func option?

**Comment by kristijanhusak** [comment]
Either that or few options like `asc`, `desc`, and then implement those option. Whichever option would work for your implementation. If you go with the custom func, note that variable needs to start with uppercase, like it's done for buffer generator (implemented here https://github.com/printbear/re-store/pull/25877)
