### ISSUE TITLE
RFE - Allow running query as selection(s) from buffer, rather than writing entire buffer? Auto-folded results when multiple outputs?

### ISSUE THREAD

**Issue by CarbonChauvinist** [kristijanhusak/vim-dadbod-ui#30]
> Is it possible to have a mapping to execute the query, instead of writing the buffer? That way you could have many queries in a file and run them individually or only some but not all.

_Originally posted by @moorecode in https://github.com/kristijanhusak/vim-dadbod-ui/issues/8#issuecomment-616239494_

Following up on the comment above. Is this possible in any way? This would be a really useful feature.

I don't know if you've used cosminadrianpopescu's sql-workbench plugin (cosminadrianpopescu/vim-sql-workbench) which I know uses SQLWorkbench/J as its back-end and thus is different from what you may have available, but his does have this feature.

Another feature that the sql-workbench plugin has that would be amazing if it could be implemented here is it automatically autofolds query output in the results buffer when run with multiple queries, or for successive queries even. The current query is always expanded, but all previous results are autofolded.

It makes it really easy to navigate between result sets in the results buffer. (I've attached a screen grab which shows an example of this for reference.)
![sqlworkbench_folded_result_sets](https://user-images.githubusercontent.com/21365869/81317692-27a88280-905b-11ea-9beb-62d8ab3def0e.png)

BTW yours is really an amazingly useful plugin! Thanks so much for creating and sharing, it is much appreciated.

**Comment by kristijanhusak** [comment]
I added the folding, please give it a test. Executing selection requires a bit more work so it will be done eventually.

**Comment by kristijanhusak** [comment]
Support for executing the selection is added.
New mapping for sql buffer is introduced, `<Leader>S`. It works in both normal and visual mode. If executed from normal mode, executes whole buffer like write, and in visual mode executes only selection.
Give it a test and and let me know if it works.

**Comment by CarbonChauvinist** [comment]
Wow, this is amazing. Thanks for considering these requests and implementing them so quickly.

I've tested executing all in Normal mode and selections in Visual mode using `<Leader>S` and this works exactly as you detailed. This, to me, brings this very close to DBeaver for my use case and current needs. Thank you. 

I also am really happy with the auto-folded results buffer as well. I do think maybe there's a slight offset in the folds though? I think you need to include an additional line instead of breaking at the blank line?

This picture shows three trivial queries run with the results all unfolded.
![dbui_all_expanded](https://user-images.githubusercontent.com/21365869/81449951-67509680-914f-11ea-805d-47e5bdf10110.png)

As you can see the result sets starts with the column names, then the returned rows, next a blank line, and then finally the number of rows affected/returned in parens.

However, when looking at the autofold results shown here the result sets stop at the blank line:
![dbui_all_folded](https://user-images.githubusercontent.com/21365869/81449915-53a53000-914f-11ea-960f-684e60b1ab71.png)

Therefore the fold for the next result set is incorrectly showing the row count of the prior query and becomes confusing to navigate.

Fixing this may also make the folds more descriptive as they would be named the columns returned for the particular query?

**Comment by kristijanhusak** [comment]
I've made folding according to output from postgres, which returns empty row betweeen the queries, and everything else has some content (no empty row between last table entry and count). Not sure how to tackle these different outputs between database types, but i'll try to figure something out.

**Comment by CarbonChauvinist** [comment]
Understood, I was just thinking to myself that the query output ending with a blank line and then another line with the number of rows returned might be specific to mssql server and might not be consistent depending on the db one is using.

**Comment by kristijanhusak** [comment]
I just pushed a small change, but I don't have sqlserver db to test with currently. Can you pull and see if it works?

**Comment by CarbonChauvinist** [comment]
Yes! Just tested and it works marvelously, thanks!
![folds_fixed](https://user-images.githubusercontent.com/21365869/81452693-8520fa00-9155-11ea-898f-e8f0c8c0b467.png)

**Comment by kristijanhusak** [comment]
Great! I just need to check mysql, it outputs things even more differently.

**Comment by kristijanhusak** [comment]
I set it up for mysql also, so it should be good to go. Closing.

**Comment by dgdosen** [comment]
Is there a command for executing on the a single selection of sql that we can remap?  I want to remap from Leader<S> to something else.

This is pretty great!

**Comment by kristijanhusak** [comment]
```vim
autocmd FileType sql nnoremap <your-mapping> <Plug>(DBUI_ExecuteQuery)
``` 

https://github.com/kristijanhusak/vim-dadbod-ui/blob/master/doc/dadbod-ui.txt#L308

**Comment by dgdosen** [comment]
Thanks - RTFM
