### ISSUE TITLE
SQL after the comment line cannot be executed correctly

### ISSUE THREAD

**Issue by tamago324** [kristijanhusak/vim-dadbod-ui#31]
Environment:

* Windows 10
* PostgreSQL

If I run the following SQL, the result will be empty.

```sql
-- comment
SELECT *
FROM information_schema.tables;
```

Also, SQL results were fetched correctly for `:%DB`.

**Comment by kristijanhusak** [comment]
Should be fixed now, give it a test.

**Comment by tamago324** [comment]
I have confirmed that the program is working properly.
Thank you for the quick fix!
