### ISSUE TITLE
Change only some icons and a config to override expanded/collapse icon

### ISSUE THREAD

**Issue by petobens** [kristijanhusak/vim-dadbod-ui#34]
Hi. I want to change the `expanded`/ `collapse` icon (i.e the open/close) triangle. I tried adding:
```viml
let g:db_ui_icons = {
    \ 'collapsed' : {
        \ 'db': ' ',
    \ },
\ }
```
but then when running `:DBUI` I get
```
Error detected while processing function <SNR>196_method[2]..115[27]..110[31]..113[30]..124:
line    5:
E716: Key not present in Dictionary: saved_queries
E15: Invalid expression: g:dbui_icons.collapsed[a:type]
```
Is it possible to override a single icon? Also is it possible to add options to override the `expanded`/ `collapsed` icons in general rather than having to manually override each pair of `expanded`/`collapsed` + `db`/`buffers`, etc?  Something like:
```viml
let g:db_ui_expanded_collapsed = ['foo', 'bar']
```

**Comment by kristijanhusak** [comment]
@petobens this should be fixed now.

**Comment by petobens** [comment]
Thanks. Any plans to distinguish between the fold marker (i.e the "triangle") and the actual icon (for instance the db)?

**Comment by kristijanhusak** [comment]
No, not really. I think it's flexible enough like this.
