### ISSUE TITLE
Show list of columns (and types) in the drawer automatically

### ISSUE THREAD

**Issue by petobens** [kristijanhusak/vim-dadbod-ui#36]
Can a feature be added to automatically show the list of columns (and types) within a table in the drawer? Currently we need to execute the `Columns`table helper to show columns. I think it would be useful to have such query executed automatically open opening a table (in order  to have quick glance of the table contents)

**Comment by kristijanhusak** [comment]
No, I don't think it's used that often. You have a "Columns" table helper (for postgres and sqlserver), so you can just open it up and run it if you need it.

**Comment by petobens** [comment]
Ok if you don't think it's useful then feel free to close this

**Comment by JDECOMBE** [comment]
Hi, 
Would love if that feature could be implemented, being able to at least see the names of the columns of a table would be much appreciated
