### ISSUE TITLE
Generate sql statements from column names 

### ISSUE THREAD

**Issue by pnetherwood** [kristijanhusak/vim-dadbod-ui#37]
I want to generate insert or update sql statements into a query buffer using the columns from a table.
Using ultisnips is one option as it gives placeholders for text entry but I'm not sure how dynamic it can be because pure generating all the possible snippets for a database wouldn't scale. Another option would be a templates option in the tree.

**Comment by kristijanhusak** [comment]
How exactly would that work? Is that your idea, or you're already using something like that in the dedicated DB tools?

**Comment by pnetherwood** [comment]
Its a feature in sql server manager:
![sqlscript](https://user-images.githubusercontent.com/11884167/82322245-1b62e480-99ce-11ea-9d6a-4059391d239a.gif)
In the example above I'm right clicking on the table and selecting script as Insert which creates the following template in the query window:
```sql
INSERT INTO [trading].[Broker]
           ([code]
           ,[name]
           ,[MIC]
           ,[location])
     VALUES
           (<code, varchar(4),>
           ,<name, varchar(50),>
           ,<MIC, char(4),>
           ,<location, varchar(50),>)
GO
```
It inserts the name and type between <> as placeholders for you to edit but they could just as easily be empty:
```sql
INSERT INTO [trading].[Broker]
           ([code]
           ,[name]
           ,[MIC]
           ,[location])
     VALUES (, , , )
GO
```
or even better filled with UltiSnips placeholders but generating the snippet on the fly might by quite hard work.
There are options for Create, Insert and Update. 

Update is:
```sql
UPDATE [trading].[Broker]
   SET [code] = <code, varchar(4),>
      ,[name] = <name, varchar(50),>
      ,[MIC] = <MIC, char(4),>
      ,[location] = <location, varchar(50),>
 WHERE <Search Conditions,,>
GO
```
and create is:
```sql
CREATE TABLE [trading].[Broker](
	[code] [varchar](4) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[MIC] [char](4) NULL,
	[location] [varchar](50) NULL,
 CONSTRAINT [PK_Broker] PRIMARY KEY CLUSTERED 
(
	[code] ASC
)
```
Create is a bit more awkward as you need to know the constraints but insert and update is pretty standard.

The simplest form of this would be to have a command which could copy a csv separated list of column names to a register then you could do what you want with it. That could even be done with a mapping in the table results Preview window.

**Comment by kristijanhusak** [comment]
I guess this could be useful, but i'm not sure where to put it. I think adding another nesting level in drawer will be too much. Sql server manager has the right click, we don't have that here.

I'm thinking maybe instead of having this out of the box, to expose some api that can be easily used to achieve this. For example:

* To expose function that can be used to query and parse results
* An event that can be hooked on to manipulate the content

So in this case, you would set up a table helper, and attach an event on it.
Then, when that event is fired (on open), you can just do the query to fetch the columns and populate the buffer with it. The event would provide all the data that it has (table, helper name, database).

This would require few lines of custom vimscript, but it would be flexible. You would be able to set it up however you want.

Thoughts?

**Comment by pnetherwood** [comment]
You're right. I don't think adding another nesting level would be a good
idea.
Perhaps you could expose s helper function that gets the column names from
an existing results preview window. That way I could call it in a mapping.

**Comment by kristijanhusak** [comment]
I exposed a public function named `db_ui#query({query})`, that takes in string as query that needs to be ran, and it returns array of arrays as result. Here's example for generating insert query for all columns in postgres (I think it works for sqlserver also):

```vimL
function! PopulateQuery() abort
  " Available buffer vars:
  " b:db
  " b:dbui_table_name
  " b:dbui_schema_name
  let rows = db_ui#query(printf("select column_name, data_type from information_schema.columns where table_name='%s' and table_schema='%s'", b:dbui_table_name, b:dbui_schema_name))
  let lines = ['INSERT INTO '.b:dbui_table_name.' (']
  for [column, datatype] in rows
    call add(lines, column)
  endfor
  call add(lines, ') VALUES (')
  for [column, datatype] in rows
    call add(lines, printf('%s <%s>', column, datatype))
  endfor
  call add(lines, ')')
  call setline(1, lines)
endfuncti

```

You just open up a table helper, and have those 3 buffer vars available. do `:call PopulateQuery()`, and it should generate insert query for all table columns in some similar syntax as you posted above.

I'm not familiar with snippets placeholder, but you should be able to generate those easily.

It requires a bit of vimscript, but can be customized however you want.
Let me know if it works for you.

**Comment by pnetherwood** [comment]
That's pretty useful. I'll look into it. Thanks.

**Comment by kristijanhusak** [comment]
Since you introduced yanking of the columns here, https://github.com/kristijanhusak/vim-dadbod-ui/pull/44, i'll consider this resolved, since there are 2 ways to somewhat achieve this.

**Comment by pnetherwood** [comment]
The more I thought about it the more I realised that a UI that does
everything is the Microsoft way not the vim way. This PR is much simpler
and probably more useful as I can use it in sql, code and other things. Sql
templates belong in one of the snippet plugins and not in dadbod-ui.
Thanks for merging.
