### ISSUE TITLE
How can you set `sql_mode` in the connection?

### ISSUE THREAD

**Issue by tshakah** [kristijanhusak/vim-dadbod-ui#45]
I've tried setting my connection string to `jdbc:mysql://localhost/thedatabase?user=theuser&sessionVariables=sql_mode=''` (and various other iterations) but it doesn't work (I'm working on a legacy system with bad SQL) - is there a way I can set the SQL mode in the connection string?

**Comment by kristijanhusak** [comment]
Try without `jdbc:`. This package supports what vim-dadbod supports, so check the docs there to see if that's possible.

**Comment by tshakah** [comment]
Thanks for the quick response! I'll go look there
