### ISSUE TITLE
Ability to cancel ongoing query

### ISSUE THREAD

**Issue by aerosol** [kristijanhusak/vim-dadbod-ui#46]
Hello. Thank you for this amazing plugin.
Currently there is no way to kill a running query when it takes forever to finish. 
Would it be possible to handle C-c or similar to drop the execution?

**Comment by kristijanhusak** [comment]
C-c should interrupt the query. 
There's a PR for vim-dadbod that adds async query running (https://github.com/tpope/vim-dadbod/pull/64), but it's still not merged.

You can use my fork until that gets merged https://github.com/kristjianhusak/vim-dadbod, and add this to your vimrc:

```
let g:db_async = 1
```

This will make all queries run async, and you can cancel them from the preview window, or by closing the preview window.

**Comment by aerosol** [comment]
Beautiful thank you!
