### ISSUE TITLE
column width in dbout is too large

### ISSUE THREAD

**Issue by tejeshreddymeka** [kristijanhusak/vim-dadbod-ui#47]
![Screenshot from 2020-06-30 17-37-35](https://user-images.githubusercontent.com/28571015/86125677-b20ce000-bafa-11ea-83db-9725dc8092b6.png)

* I am not able to control the width of column in dbout.
* and also auto completion for keyword (like `insert`, `select`,...) is not working even after installing `coc-db`

* I am using neovim and connected to mssql server

**Comment by kristijanhusak** [comment]
dbout output is completely handled by [vim-dadbod](https://github.com/tpope/vim-dadbod).
I'm not sure if this can be configured somehow.
@pnetherwood do you maybe have some advice how to reduce width of the columns for mssql?

Autocompletion only autocompletes tables,schemas and columns. It is not a full completion framework.

**Comment by tejeshreddymeka** [comment]
> dbout output is completely handled by [vim-dadbod](https://github.com/tpope/vim-dadbod).
> I'm not sure if this can be configured somehow.
> @pnetherwood do you maybe have some advice how to reduce width of the columns for mssql?
> 
> Autocompletion only autocompletes tables,schemas and columns. It is not a full completion framework.

OK.

Thanks for the quick reply.

**Comment by tejeshreddymeka** [comment]
I came to know that in `vim-dadbod` the raw output from `sqlcmd` tool is printing into to `dbout` (in the case of `mssql`).   
Should i have to write some parsing function on my own the can parse the `dbout` content or is there any other way ?

By the way @kristijanhusak  , your `vim-dadbod-ui` is owesome.

**Comment by kristijanhusak** [comment]
You should be able to provide custom width for columns. Check this comment:
https://github.com/kristijanhusak/vim-dadbod-ui/pull/26#issuecomment-622968185

And this SO question: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b6f2314c-1ecb-43fc-b881-2d2df7c9c457/setting-individual-column-width-in-sqlcmd-outut?forum=sqltools

I think combining these two should help you solve the issue.

**Comment by tejeshreddymeka** [comment]
Thanks for the links. I am able to configure the columns width.

**Comment by pnetherwood** [comment]
sqlcmd will size the columns based on the field width up to a maximum (default 80) but only if it knows how long the field is. If you do some manipulation in the select statement it won't know how big the field is and will set it to the maximum. That's what's happening with the output of sp_help (which is why I added the Columns item in vim-dadbod-ui so it all fit nicely on the screen)
Its possible to pass parameters to sqlcmd "under the covers" using a an ini file. Search google for SQLCDMINI.

**Comment by tejeshreddymeka** [comment]
@pnetherwood  Yeah I have set ‘SQLCMDINI’ to use ‘init.sql’ which contains 
`
:setvar SQLCMDCOLSEP "|"`

`:setvar SQLCMDMAXFIXEDTYPEWIDTH 20`

`:setvar SQLCMDMAXVARTYPEWIDTH 50 `

There is another option that we can use`sqlcmd -W` which remove trailing spaces in each column and it best fits to the screen. 
But I’m not able to find the var that I need to set to get that functionality.

May I know which var I need to set to get best column width to fit nicely to the screen.

**Comment by pnetherwood** [comment]
I don't know if they're is one. Certainly not according to this list:
https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-use-with-scripting-variables?view=sql-server-ver15#sqlcmd-scripting-variables

**Comment by tejeshreddymeka** [comment]
Ok thank you.

**Comment by 0re5ama** [comment]
> ` :setvar SQLCMDCOLSEP "|"`
> 
> `:setvar SQLCMDMAXFIXEDTYPEWIDTH 20`
> 
> `:setvar SQLCMDMAXVARTYPEWIDTH 50 `

I am facing the same issue and I don't know how to set these. Do I set it in the connection string? Or do I set it in my lazygit configuration of dadbod-ui? Also, init.sql doesn't look like an sql file
