### ISSUE TITLE
DotenvGet doesn't support .envrc files

### ISSUE THREAD

**Issue by jc00ke** [kristijanhusak/vim-dadbod-ui#48]
I can get at a single database by exporting `DBUI_URL` but I'm not able to use the `DB_UI_*` env vars to populate the connections. I'm not sure if we can work around it here or if I should raise the issue over at `Dotenv`.

**Comment by kristijanhusak** [comment]
Are you sure you are naming your env file correcty? In title it says `.envrc`, but it should be `.env`.

**Comment by jc00ke** [comment]
Yeah, that's the issue I'm running into: I use `direnv` not `dot-env` and `direnv` uses a `.envrc` file.

If I set `export DB_UI_DEV=...` in my `.envrc` then I'll see the value when I `:echo DotenvGet("DB_UI_DEV")` from within `neovim`.

But if I :echo DotenvGet()` I get `{}`.

(Apologies if the calls aren't quite correct, I'm on my phone and going off memory.)

**Comment by kristijanhusak** [comment]
Try running this when you open up vim `:Dotenv .envrc`. It should load up env vars from that file, according to the vim-dotenv readme. https://github.com/tpope/vim-dotenv#interactive-usage

**Comment by jc00ke** [comment]
I gave that a try and DB UI doesn't pick it up even though I can `:echo` the value.
I even tried adding a new ENV var to my `.envrc` file, loading with `:Dotenv .envrc` and then `:echo`'ing and I saw the value. DB UI doesn't seem to recognize it though. I opened and closed the DB UI drawer and used `R` to try to reload.

Thanks for helping me debug this.

**Comment by kristijanhusak** [comment]
The problem is that when you execute the command, it loads the vars into the environment, but it doesn't save it on the buffer variable, which is properly done when using default `.env` file. Dbui tries to load all vars from the buffer variable which is empty in this case. You can trigger loading manually so dbui can read it.

Adding this to your vimrc should make it work:
```vim
autocmd User DBUIOpened let b:dotenv = DotenvRead('.envrc') | norm R
```

**Comment by jc00ke** [comment]
That `autocmd` worked; I hadn't thought of that. Thank you!
