### ISSUE TITLE
Load database error

### ISSUE THREAD

**Issue by glepnir** [kristijanhusak/vim-dadbod-ui#50]
Hi @kristijanhusak   
I use three different database connections, but after opening dadbod, I found that they are all connected to `mysql`.
the `echo g:dbs`
```vim
{'jianshu':'mysql://root@localhost/jianshu','ginweb':'mysql://root@localhost/ginweb'}
```

![image](https://user-images.githubusercontent.com/41671631/89152338-88315800-d595-11ea-8416-837713b1300d.png)

**Comment by glepnir** [comment]
Hi @kristijanhusak  any update for this issue?

**Comment by kristijanhusak** [comment]
@glepnir I'll look into this. Did you try declaring different formats to see if it works?
For example, try something like this to see if you get the same results:
```vimL
  let g:dbs = [
  \ { 'name': 'jianshu', 'url': 'mysql://root@localhost/jianshu' }
  \ { 'name': 'ginweb', 'url': 'mysql://root@localhost/ginweb' },
  \ ]
```

**Comment by glepnir** [comment]
@kristijanhusak  I already tried it. the result is same.

**Comment by kristijanhusak** [comment]
@glepnir as far as I know, in MySQL, all databases belong to the same schema. From your screenshot, I see both databases in both connections.
How would you expect it to work?

**Comment by glepnir** [comment]
@kristijanhusak  you can see the `crawler` and `ginweb` both connect to `mysql db`. not `ginweb` database

**Comment by glepnir** [comment]
I tried the dadbod `DB mysql://root@localhost/ginweb`. it's only connect to ginweb database.

**Comment by kristijanhusak** [comment]
@glepnir all mysql databases belong to `mysql db`, that's why you see them in both connections.
Schemas are fetched from this query:
```sql
SELECT schema_name FROM information_schema.schemata
``
What would you expect to see in "Schemas" when you connect to specific database?

**Comment by glepnir** [comment]
To be honest, this statement is correct. It will return all databases in mysql。But just like the connected url. We want to connect to a certain database.Any current mysql connection url returns the entire mysql database.
This is strange. Why do we need to specify a certain database in the URL? Even if it is specified, it loses meaning. Because we still see all the databases in mysql.
```
ginweb: mysql://root@localhost/ginweb  same as mysql:mysql@localhost/mysql
crawler: mysql://root@localhost/crawler  same as mysql:mysql@localhost/mysql
```

**Comment by kristijanhusak** [comment]
@glepnir I don't think you have to. Doing `mysql://root@localhost` should be enough.

**Comment by glepnir** [comment]
Ok. But this is not important. What I want to say is that even if we connect to the specified database through the URL, the result is still the entire mysql database.

**Comment by kristijanhusak** [comment]
@glepnir Yes, that's true. That's why I ask, what would you expect to be listed under 'Schemas' in drawer when you are connected to specific database?

**Comment by glepnir** [comment]
Obviously I only want to see information about this database. Maybe like this? `ginweb: mysql://root@localhost/ginweb`
![image](https://user-images.githubusercontent.com/41671631/90020891-0eab0f80-dce3-11ea-8100-080db43b9da7.png)

**Comment by glepnir** [comment]
It looks like we need to query the views functions tables from schemes. I don't know the specific implementation. If we can't achieve it. I think we need to modify the readme and doc to remind other users. Any URL in mysql will return the entire mysql database. To avoid more trouble

**Comment by kristijanhusak** [comment]
@glepnir pull latest and give it a test.
It should print out whole mysql db only if url doesn't have specified db (`mysql://root@localhost`).
If db is specified, it should show only tables.

**Comment by glepnir** [comment]
It looks good, but can there be 2 tables hidden?
![image](https://user-images.githubusercontent.com/41671631/90022545-3ef3ad80-dce5-11ea-95ff-c1ef3e46d267.png)

**Comment by kristijanhusak** [comment]
Can you give me output of this:
```vimL
:echo db#adapter#mysql#tables('mysql://root:root@localhost/ginweb')
```

I want to see what's that warning.

**Comment by glepnir** [comment]
Here is warning.
![image](https://user-images.githubusercontent.com/41671631/90024156-22587500-dce7-11ea-92ad-296011a13194.png)

**Comment by kristijanhusak** [comment]
@glepnir I edited my comment. I initially added the password for root. Do this:
```vimL
:echo db#adapter#mysql#tables('mysql://root@localhost/ginweb')
``

**Comment by glepnir** [comment]
> Can you give me output of this:
> 
> ```viml
> :echo db#adapter#mysql#tables('mysql://root@localhost/ginweb')
> ```
> 
> I want to see what's that warning.

`:echo db#adapter#mysql#tables('mysql://root@localhost/ginweb')` this command same as pre command? The output is same as pic ? Do i need update the dadbod-ui?

**Comment by kristijanhusak** [comment]
@glepnir put whatever you put for url in dadbod-ui.
From screenshot it looks like you provided a password for root, but you are not using any password.
If you are using password for root, do it like this:
```
:echo db#adapter#mysql#tables('mysql://root:YOURPASSWORD@localhost/ginweb')
```

**Comment by glepnir** [comment]
Got it .
![image](https://user-images.githubusercontent.com/41671631/90025502-bd9e1a00-dce8-11ea-8f74-866768ca5d4b.png)

**Comment by kristijanhusak** [comment]
@glepnir pull latest changes and give it a test.

**Comment by glepnir** [comment]
Does not hidden this in latest version?
![image](https://user-images.githubusercontent.com/41671631/90026835-6b5df880-dcea-11ea-8d55-6cec43a28b22.png)

**Comment by kristijanhusak** [comment]
@glepnir sorry, I don't get the warning, so I can't test it properly. Regex was wrong. Pull and test again.

**Comment by glepnir** [comment]
https://github.com/kristijanhusak/vim-dadbod-ui/blob/945f4eeafdb1a8e94d3cb0f3e91c64b906b195bf/autoload/db_ui/drawer.vim#L524

What about this?
```vim
let a:db.tables.list = a:db.tables.list[2:len(a:db.tables.list)-1]
```

**Comment by glepnir** [comment]
I create a pr for this. please check thanks.

**Comment by kristijanhusak** [comment]
@glepnir it will not work. I wrote on PR why. Try to go to line 524 in drawer.vim and tweak the filtering.

**Comment by kristijanhusak** [comment]
@glepnir pull now and test. Closing square bracket wasn't escaped properly.

**Comment by glepnir** [comment]
closed.
