### ISSUE TITLE
Can't auto execute table helpers when not executing on save

### ISSUE THREAD

**Issue by petobens** [kristijanhusak/vim-dadbod-ui#53]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/kristijanhusak/vim-dadbod_async-query
set runtimepath+=$DOTVIM/bundle/repos/github.com/kristijanhusak/vim-dadbod-ui
filetype plugin indent on


let g:db_ui_auto_execute_table_helpers = 1
let g:db_ui_execute_on_save = 0
" let g:dbs = _some_postgres_db

augroup ps_dadbodui
    au!
    au Filetype dbui nmap <silent><buffer> <CR> <Plug>(DBUI_SelectLine)
augroup END
```
If I now run  `:DBUI` and press enter on one of the postgres tables `List` or `Columns` queries then the helper query is not auto executed. If I now change `g:db_ui_execute_on_save` to `1` then it is. I don't know if this is a bug or a feature.

**Comment by kristijanhusak** [comment]
I'd say it's a bug. I didn't consider usage of those two at the same time. auto execute depends on execute on save, because it just writes the buffer. I'll fix it.

Today I added <CR> as part of the default mappings for open, so you don't need to bind that manually.

**Comment by kristijanhusak** [comment]
@glepnir this should be fixed now. Please give it a test.

**Comment by glepnir** [comment]
@kristijanhusak   Are you mention wrong people?

**Comment by kristijanhusak** [comment]
@glepnir sorry.

**Comment by petobens** [comment]
Seems to work. Thanks!
