### ISSUE TITLE
Env vars not utilized properly unless loaded from the start

### ISSUE THREAD

**Issue by pricheal** [kristijanhusak/vim-dadbod-ui#59]
I am using vim-dotenv to load database connection strings from a `.env` file that exists directly in my home directory (~/.env). The problem I am having is that it seems like this plugin only recognizes the env vars sourced by vim-dotenv if they are sourced automatically (when vim starts). If I source more env vars interactively with `:Dotenv {dir}` (from vim-dotenv), the connections don't show up when I do `:DBUI`.

The reason I need to do this is because vim-dotenv seems to only source the first `.env` file that it finds up the directory tree. So if I am in a project with its own directory (that exists in my home directory) that has its own `.env` file, the `~/.env` file does not get sourced (and doesn't show up when I do `:DBUI`).

Is there anyway to make this work? My goal is to call something in my `.vimrc` that manually sources `~/.env` directly on vim startup, that way I can always call `:DBUI` and see all my connections (even if I didn't open a file directly -- side note, why do the env vars for connections not work properly if you don't actually open a file with vim?)

Thanks for any help, great plugin by the way -- surprised it is not more popular.

**Comment by kristijanhusak** [comment]
Should be fixed now. Just make sure to redraw the drawer once you load the env.

Problem was that I was solely relying on `DotenvGet()`, which doesn't always work as expected.
Now I check all available env variables.

**Comment by pricheal** [comment]
> Should be fixed now. Just make sure to redraw the drawer once you load the env.
> 
> Problem was that I was solely relying on `DotenvGet()`, which doesn't always work as expected.
> Now I check all available env variables.

You rock!
