### ISSUE TITLE
Results window disappears before executing the new query

### ISSUE THREAD

**Issue by milind-shakya-sp** [kristijanhusak/vim-dadbod-ui#64]
Looks like the results window disappears as soon as the mode is changed for e.g from visual to insert.

Would help if the previous query results stay in the window until the new query is executed.

**Comment by kristijanhusak** [comment]
I'm not able to reproduce that.
Can you give me minimal vimrc, some details about your system and vim/neovim, and reproducible steps? Thanks.

**Comment by milind-shakya-sp** [comment]
NVIM v0.4.3
macOS - Catalina
reproducible steps:

  - Run a query in the query window
  - Results pop up in the pop up window (query window switches from insert to visual mode)
  - Go back to query window and switch to insert mode.
  - results window dissapears.

The only workaround that seems to work for me, is to split the results window into another vertical window, so when i switch to insert mode, even though on result window vanishes, I still have another one left.

**Comment by kristijanhusak** [comment]
How exactly are you running the query?
By saving a query buffer, using `<Leader>s` mapping from visual mode, or something else?

Did you try with minimal vimrc (only vim-dadbod and vim-dadbod-ui installed) ? If not, please give that a try.

Your pop up window (which is a preview window I presume), shouldn't get focus, so i'm not sure how you get into the state where you need to go back to the query window. Your query window should never lose the focus.

**Comment by milind-shakya-sp** [comment]
Yes, I have the <Leader>s mapping from visual mode, which is what I use to run the query.
