### ISSUE TITLE
Set filetype based on connection url

### ISSUE THREAD

**Issue by helmecke** [kristijanhusak/vim-dadbod-ui#65]
Hi, great plugin thanks for sharing.

It would be great if `New query` would set filetype based on database connection url, like `mysql` for `mysql://127.0.0.1/test`.

**Comment by kristijanhusak** [comment]
Is there any advantages of `mysql` filetype over `sql` filetype besides colors?

**Comment by helmecke** [comment]
Depends on the specific vim configuration. But snippets or autocomplete come to mind. Maybe it's just an OCD thing.

**Comment by kristijanhusak** [comment]
Mysql connections should now get `mysql` filetype set for queries, and Oracle will get `plsql`.
I would appreciate if both of you would test to see if it works as expected.

**Comment by eruizc-dev** [comment]
I don't have any OracleDB at the moment to test, but mysql databases work as intended! Amazing work

**Comment by radojka11** [comment]
@kristijanhusak i just tested it for a plsql file type and the query result pane does not pop up. However when i change the filetype name manually from plsql to sql it works as expected.

**Comment by kristijanhusak** [comment]
@radojka11 does it work for mysql or postgres?
