### ISSUE TITLE
Global variables g:db_ui_* VS g:dbui_* are misleading

### ISSUE THREAD

**Issue by bew** [kristijanhusak/vim-dadbod-ui#66]
Hello,
I think that the use of variables `g:db_ui_*` (for config) & `g:dbui_*` (in the plugin) are misleading, what I mean is that when I look at the source code of the plugin and find a g: variable, and I try to override it in my config, it does nothing.

For example, I wanted to disable to execution on write. Since I didn't see the option documented in the top readme (and didn't thought at checking the `:h` pages at that time, and went to check the source code and found
https://github.com/kristijanhusak/vim-dadbod-ui/blob/ed73c98c9c5f631f390b651e46e22c04d44420b3/autoload/db_ui/query.vim#L184-L186
So I figured that setting `g:dbui_execute_on_save` to v:false (or 0) would disable this behavior.
Unfortunately, that variable is overwritten by
https://github.com/kristijanhusak/vim-dadbod-ui/blob/a0045ae2ca9393e7831c0d72e20678d33a00eb90/plugin/db_ui.vim#L19
which takes its value from `g:db_ui_execute_on_save` instead.

Why did you do this distinction? Would it be possible to keep a single source of truth, and maybe change all `g:dbui_*` to `g:db_ui_*` with default if they are not already set?

**Comment by kristijanhusak** [comment]
`g:db_ui` vars are for the user to change, where `g:dbui` is for internal purposes. I think I had some issues with tests or something, can't really remember at this moment.
I agree it's a bit misleading, but didn't really think about it since I presume that who checks the source code, can figure it out :)

Yeah, it could be unified, why not.

**Comment by kristijanhusak** [comment]
I updated this. Names are now unified. Thanks for reporting.
