### ISSUE TITLE
Cannot open DBUI after inputing wrong db address

### ISSUE THREAD

**Issue by etrnal70** [kristijanhusak/vim-dadbod-ui#69]
Recently i'm inputing a wrong mysql address format (mysql://localhost@user/dbname) and now `:DBUI` cannot be opened.

`
Error detected while processing function db_ui#open[1]..<SNR>102_init[2]..9[25]..11[10]..12;
line 10:
E716: Key not present in Dictionary: "path /=? '/'"
E15: Invalid expression: schema_support && tolower(scheme) =? 'mysql' && parsed_url.path /=? '/'
`
Tried to remove dadbod-ui with `PlugClean` and reinstalling it again, but the result are the same.

**Comment by kristijanhusak** [comment]
Pull the latest master and give it a try.

**Comment by etrnal70** [comment]
Tried latest. Still the same error

**Comment by kristijanhusak** [comment]
I tried your example url (`mysql://localhost@user/dbname`), it properly parses it. 
What do you get when you do this:
```
:echo db#url#parse('mysql://localhost@user/dbname')
```

**Comment by etrnal70** [comment]
I got `{'params': {}, 'scheme': 'mysql', 'opaque': '//localhost@user/dbname'}`

**Comment by kristijanhusak** [comment]
Hmm, that's odd.
Please provide some additional information:
* OS
* Vim/Neovim + Version

**Comment by etrnal70** [comment]
Maybe cleaning the DBUI data can fix it ? I've tried PlugClean though

**Comment by etrnal70** [comment]
OS : Linux
Neovim : v0.5.0-843-gce70edb80

**Comment by kristijanhusak** [comment]
What's the output of this from terminal?
```
cat ~/.local/share/db_ui/connections.json
```

**Comment by etrnal70** [comment]
No such file or directory

**Comment by kristijanhusak** [comment]
How did you add your connection?

**Comment by etrnal70** [comment]
I usually add mine from DBUI, looks like it calls `:DBUIAddConnection`. It always works before, but after i input the wrong format, looks like it stuck

**Comment by etrnal70** [comment]
Looks like it also has some extra message
`Error detected while processing function db_ui#open:
line 2:
E121: Undefined variable :drawer
E15: Invalid expression: s:dbui_instance.drawer.open(a:mods)`

**Comment by kristijanhusak** [comment]
Something really strange is happening.
Give me this information:
* what's the output of `:echo g:db_ui_save_location`
* what's the output of `:echo g:dbs`
* Do you have any env variables that start with `DB_UI`? Check by pressing tab on `echo $DB_UI`

**Comment by etrnal70** [comment]
g:db_ui_save_location give me my wuery fooder (~/Queries)
g:dbs `E121: Undefined variable: g:dbs`

I didn't set any env variable related to DB_UI

**Comment by kristijanhusak** [comment]
Do you have `~/Queries/connections.json` file? What's the output of it?

**Comment by etrnal70** [comment]
Well thats it. Deleting all the entries from connections.json solve the problem.

**Comment by kristijanhusak** [comment]
Great. I'm still confused how you get different output for `db#url#parse` for the same url.

**Comment by etrnal70** [comment]
I don't know either about that 😂. Anyway, thank you for your assistance and effort !

**Comment by cristianUrbina** [comment]
> What's the output of this from terminal?
> 
> ```
> cat ~/.local/share/db_ui/connections.json
> ```

Just for future references. I had the same problem, and the only difference is I actually have my connections stored here in this file. Deleting the failing connection solves the problem (it is not necessary to delete all your connections), which might be the last one you just added.
