### ISSUE TITLE
Open query (DBUI_SelectLine) - always open in drawer

### ISSUE THREAD

**Issue by moorecode** [kristijanhusak/vim-dadbod-ui#7]
Is it possible to have the database query always open in the drawer at the bottom of the window, instead of in another buffer?

**Comment by kristijanhusak** [comment]
You mean in the horizonal split?

**Comment by moorecode** [comment]
I mean is it possible to use the drawer that the results are displayed in as the buffer for the query.

**Comment by kristijanhusak** [comment]
How would that work? What would you do when you need the drawer again?

**Comment by moorecode** [comment]
The drawer would be the "SQL buffer", that swaps between a query and results, each time you select a query in the side bar it opens in the drawer, and when you execute it the results replace the query.

**Comment by kristijanhusak** [comment]
dadbod opens results in the preview window, that can't be manipulated much, and it's really hard to change that functionality or hijack it. So i would say it's not possible.

**Comment by kristijanhusak** [comment]
I maybe didn't understand what you are saying. Do you want to have like a single window, where drawer would show, and when you select a query from drawer, to open it directly in same window, with ability to again open drawer there?
I'll try to set up something like that because i think it will be useful.

**Comment by moorecode** [comment]
Yeah something similar, pick a query from the side bar, it opens in the in the drawer, when its executed the results show in the drawer.
```
+---+--------------+
|   |              |
|   |              |
| s |              |
| i |              |
| d |              |
| e +--------------+
| b |query/results |
| a |drawer        |
| r |              |
+---+--------------+
```

**Comment by kristijanhusak** [comment]
For me, drawer is sidebar in your case.
I cannot reuse same window for both query and the results of the query. I thought you want something like this:
```
// Only drawer
+-----------------------+
| - db                  |
|   +query              |
|                       |
|                       |
|                       |
+-----------------------+
```

```
// Opened new query in same window
+-----------------------+
| select* from tbl;     |
|                       |
|                       |
|                       |
|                       |
+-----------------------+
```
```
// Executed query
+-----------------------+
| select* from tbl;     |
|                       |
|                       |
|                       |
|                       |
+-----------------------+
| Query results         |
+-----------------------+
```
```
// Reopen drawer in same window
+-----------------------+
| - db                  |
|   +query              |
|   -buffers            |
|     query *           |
|                       |
+-----------------------+
| Query results         |
+-----------------------+
```
