### ISSUE TITLE
Cannot modify some queries after execute

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#71]
Is it intentional behaviour in some case? I encounter it since setting `let g:db_ui_tmp_query_location = './.ide/dbui/queries'`. This directory is writable, it didn't have to be created manually and I still have no problem with saving any fresh query there.

**Comment by kristijanhusak** [comment]
I have similar issue with writing things to ~/Dropbox folder, but I wasn't able to figure out why is that happening. I see that you are using relative path. Can you try using the absolute path and see if it helps? I presume you keep it like this to have it per project, but for test purposes please use absolute path.

**Comment by przepompownia** [comment]
`let g:db_ui_tmp_query_location = getcwd().'/.ide/dbui/queries'` - no problem, especially that it is executed from `.exrc`. I'll give feedback after some time.

**Comment by kristijanhusak** [comment]
I figured it out. Code for finding dbui drawer window was bad. It considered query window a drawer because it has `dbui` in name. Should be working now.

**Comment by przepompownia** [comment]
I did not encounter this issue as of this change. Thanks!
