### ISSUE TITLE
Allow configuration for starting with expanded selected lists

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#75]
I would like to have settings (per project) that start `DBUI` with some items expanded. 

Please see #74 (as an example for expanding table list for selected database) how we could implement it. 

In the next step I would like to have cursor placed at the top of tables list.

**Comment by kristijanhusak** [comment]
Custom autocmd is fired when DBUI is opened. You can use something like this to achieve what you want.

```vim
autocmd User DBUIOpened call s:open_db()

function! s:open_db()
  "Find db.
  call search('dev')
  "Open db
  norm o
  "Find tables
  call search('Tables')
  "Open tables
  norm o
endfunction

```

**Comment by przepompownia** [comment]
This four-line simulation of manual actions has enoughly simple expression to close the mentioned PR ;-)
