### ISSUE TITLE
Can't list table User

### ISSUE THREAD

**Issue by eruizc-dev** [kristijanhusak/vim-dadbod-ui#77]
### Issue

I have a table named `User` that I cannot retrieve without modifying the default query.

### Repro steps

 1. Open `:DBUI`
 2. Navigate to a table named `User`
 3. Select the `~ List` option
 4. The generated query is `select top 200 * from User
 5. Execute the previously generated query
 6. Error:

```
Msg 156, Level 15, State 1, Server <server>, Line 1
Incorrect syntax near the keyword 'User'.
```

### Workaround

Add brackets around the table name

```sql
select top 200 * from [User]
```

### System info

 -  vim: nvim v0.5.0-828-g0a95549d6 (nightly)
 - dadbod: built from source, commit [4a2a8b](https://github.com/tpope/vim-dadbod/commit/4a2a8bc6dca50bc58885bdf2c0a153d0990d7872)
 - dadbod-ui: built from source, commit [2281e0](https://github.com/kristijanhusak/vim-dadbod-ui/commit/2281e0066f153f1bd80eec2c02a72f7bf1660884)
 - Database: [mssqlserver:latest](https://hub.docker.com/_/microsoft-mssql-server) running in docker
 - Database driver: Microsoft ODBC Driver for SQL Server 17

### Additional info

There is a related issue: #73

**Comment by kristijanhusak** [comment]
Are square brackets in mssql same thing like quotes in postgres?

**Comment by eruizc-dev** [comment]
I've never used postgres. But in mssql you put square brackets around identifiers (database, tables, column names and others) to avoid conflicts with keywords.

https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?redirectedfrom=MSDN&view=sql-server-ver15

**Comment by kristijanhusak** [comment]
This should be fixed now.

**Comment by eruizc-dev** [comment]
@kristijanhusak it works! Thank you very much
But watching the commit I believe someone may run into trouble later since the syntax is as follows:

```sql
select top 200 * from [schema].[table]
```

And from what I'm seeing it would generate the following:

```sql
select top 200 * from schema[table]
```

Is this correct? Want me to open a new issue? Maybe submit a PR on it?

**Comment by kristijanhusak** [comment]
It is `schema. [table] `. I'm not adding brackets to schema. I don't think people usually name the schema by reserved word.
