### ISSUE TITLE
Parametrized queries are executed even without assigned value

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#78]
Reproduction: 
- execute any parametrized query
- on the prompt press `ESC` instead of entering any value.

Unlike expected, 
- the query is executed
- the empty value is saved and require to be deleted

**Comment by kristijanhusak** [comment]
`ESC` doesn't send "Interrupt" code for inputs, `CTRL-c` does. I fixed it so CTRL-c always properly cancel the input actions.

**Comment by przepompownia** [comment]
Good to know how to correctly interrupt the action. 

The only remaining thing is the notification
```
[DBUI]                                                                                                                                                                                               
Executing query...
```

**Comment by kristijanhusak** [comment]
That should be fixed now, please give it a test.
