### ISSUE TITLE
how to customize table layout

### ISSUE THREAD

**Issue by alex-popov-tech** [kristijanhusak/vim-dadbod-ui#87]
I saw in readme on the screen that there are pluses used as vertical boundaries, but see nothing about such customizations in docs :(

**Comment by kristijanhusak** [comment]
Which database are you using?

**Comment by alex-popov-tech** [comment]
sqlite

**Comment by kristijanhusak** [comment]
Each database have different output. Screenshots show postgres database.

**Comment by alex-popov-tech** [comment]
oh, you don't modify output...ok, thanks!
