### ISSUE TITLE
Missing Schemas

### ISSUE THREAD

**Issue by SergioShz** [kristijanhusak/vim-dadbod-ui#88]
Hi,

Everything was good until I run last update in vim (Using vim-plug), now schemas from Postgres DBs are missing:

![image](https://user-images.githubusercontent.com/39086495/110482461-fcfae080-80e8-11eb-99d0-4ceeb066f775.png)

I have several connections and this happen in all my connections for both Postgres and Redshift, connections to Mysql DBs shows schemas as usual.

Any way to debug and see what's happening?

Thanks!

**Comment by kristijanhusak** [comment]
It may be related to this commit: https://github.com/kristijanhusak/vim-dadbod-ui/commit/dbb56909233e880776270416e4b74a52155a3080

Can you try checking out to commit before that (https://github.com/kristijanhusak/vim-dadbod-ui/commit/46d1c63c0a6d63f67f6658d33c0b30c41a44c612) and see if it works?

**Comment by kristijanhusak** [comment]
Try checking out this commit and see if it works: https://github.com/kristijanhusak/vim-dadbod-ui/commit/f7b0de14f98eda1f5c6d0271d5df2f189c8ec132.

**Comment by kristijanhusak** [comment]
I have no idea what it could be. There were no any bigger changes since you added that PR. I'm using postgres on daily basis and I don't have any issues with it.
Can you try go back commit by commit and see if that helps?

**Comment by SergioShz** [comment]
yes, I'll try that, 
thanks.

**Comment by SergioShz** [comment]
I found it, seems that this commit was the problem https://github.com/tpope/vim-dadbod/commit/d3fce38678e1a10c62eb46ac5bf54dec05cc88, reverting to the previous one has fixed the issue. I'll investigate more to see what was the actual problem, for the moment I'm happy with this.

**Comment by kristijanhusak** [comment]
Could be, I'm using my fork of vim-dadbod because of async support. You can switch to my fork until i rebase from upstream.

**Comment by SergioShz** [comment]
Nice, I think we can close this, thanks!

**Comment by kristijanhusak** [comment]
I fixed it now to be compatible with the Tpope's dadbod, so you can go back if you want.

**Comment by SergioShz** [comment]
Nice!! Updated vim-plug and working fine! 🙂
