### ISSUE TITLE
Postgresql psql --quiet option

### ISSUE THREAD

**Issue by RRikor** [kristijanhusak/vim-dadbod-ui#89]
Is there a way to add a --quiet option to the postgresql connection? Without --quiet, by default psql displays configuration messages set in ~/.psqlrc at the start, and these are interpreted by vim-dadbod-ui as schemas:

query output:
![image](https://user-images.githubusercontent.com/6231663/111277306-9ae63200-8638-11eb-894b-e5a5d29307cf.png)

vim-dadbod-ui schemas:
![image](https://user-images.githubusercontent.com/6231663/111277379-ad606b80-8638-11eb-9d7a-6869b1544948.png)

the cause:
![image](https://user-images.githubusercontent.com/6231663/111277745-10ea9900-8639-11eb-8f2b-6fdb21600f45.png)

**Comment by kristijanhusak** [comment]
You can set QUIET in your psqlrc like this:
```
\set QUIET 1
\pset null '(null)'
\set QUIET 0
```
