### ISSUE TITLE
Saved connections should be canonicalized

### ISSUE THREAD

**Issue by tpope** [kristijanhusak/vim-dadbod-ui#90]
If I add the connection `sqlite:db.sqlite3` and `:cd`, the connection breaks. To solve this, use `db#resolve(url)` to convert it to a canonical form. This throws an exception if the connection URL is invalid, so it can also fill any need for validation.

**Comment by tpope** [comment]
I think you want to do this earlier, where you call `db#url#parse()`, so the name will reflect the correct location, and so that the non-URL variants like `./db.sqlite3` will work.

**Comment by kristijanhusak** [comment]
Thanks. Fixed it.
