### ISSUE TITLE
Allow option to turn off prompt for bind parameter.

### ISSUE THREAD

**Issue by Fedreg** [kristijanhusak/vim-dadbod-ui#91]
First off, fantastic work on this!! 

It has become a very useful tool for me so thank you for sharing it!

I have a very specific issue that probably won't affect too many users..

I write a lot of Clojure and sometimes stick small blobs of [EDN](https://github.com/edn-format/edn) data in my SQL tables.

So I might have a query such as
``` 
update user_config set user_settings = '{:account 123 :foo :bar}` where id = 1; 
``` 
etc...
dadbod-ui sees the `:account` keyword as an attempt to bind a parameter and will not run the query.   This happens even if that query is commented out and I'm trying to run a different uncommented query in the same window

I was wondering if we can either
Not have dadbod-ui prompt for binding if something is commented out
OR
Add a new setting to turn off parameter binding.

I'm not terribly experienced vimscript writer but I can take a first stab at it if you'd like (and with your blessing) since I know this is a very specific request.  Probably affects just a few Clojure and Elixir users (maybe a few other niche langs)

**Comment by kristijanhusak** [comment]
I didn't account for this :)

I could add a quick setting that would disable binding parameters, but I think I should improve the regex that finds the proper bind parameters.

When you get prompts for these just press Enter through them without entering anything, it should consider them invalid and not prompt you any more. This is tied to buffer, so creating new buffer has the same issue unfortunately.

**Comment by Fedreg** [comment]
Yes, it's a very specific issue :)

> When you get prompts for these just press Enter through them without entering anything, it should consider them invalid and not prompt you any more.

I just tried this and it worked perfectly for my use case.  So no need to make any changes on my account, even for me this doesn't come up very often and your workaround is more than sufficient.

Thanks for the quick reply!

**Comment by kristijanhusak** [comment]
This should be fixed now. Bind params inside strings are now ignored.
Note that in your example above your value is closed with backtick (`), not single quote, so it will not work if you copy paste it.

This example:
```sql
update user_config set user_settings = '{:account 123 :foo :bar}' where id = :id
```

Should prompt only for `:id` param.

**Comment by Fedreg** [comment]
@kristijanhusak 

Pulled in your changes and verified it is working as described 👍 

Thanks for the quick fix!!!
