### ISSUE TITLE
[neovim] Notification dialog overlaps the query result

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#93]
Right after executing query I have to wait 7 second (hardcoded `let s:delay = 7000`) until notification message disappears:

![image](https://user-images.githubusercontent.com/11404453/113476996-556e9500-947f-11eb-8570-ca82abbf72c2.png)

I found that the notification API allows using echo instead
```
call db_ui#notifications#info('Executing query...', {'echo': 1})
```
but it seems to be not used by `s:query.execute_query(...)`.

**Comment by przepompownia** [comment]
Independently of position of such window it would be good to allow simply close it by some mapping, for example, `<Plug>(DBUI_Close_notifications)`.

**Comment by kristijanhusak** [comment]
It should not overlap the results but instead be above them. I'll check.
Clicking on it (focusing the notification) should immediately hide it.

**Comment by przepompownia** [comment]
Indeed, clicking closes it, but keyboard action (I have `Esc` for float windows coming from CoC) would be more convenient. 

I have no good idea where such window could be placed when the result window have no free space. Sometimes there is a lot of empty lines at the bottom of the result window.

**Comment by kristijanhusak** [comment]
This should be fixed now.
Notification should appear above the out window, not in the bottom right corner.
Also, I added a command `:DBUIHideNotifications` that should hide any notifications that are currently visible.

**Comment by przepompownia** [comment]
Thanks for  acdf245, The new command (or configuration that forces using echo) can be still needed despite it.

Please test execute a query, go  the dbout window, `resize +10` on it and execute the query again. 

![image](https://user-images.githubusercontent.com/11404453/113487518-ddbd5c00-94b8-11eb-8854-64de32c7f466.png)

I have not found how to configure (percent or line) height of the dbout window.

**Comment by kristijanhusak** [comment]
Ah, yeah, that case is not considered. I take `&previewheight` to figure out the position. I'll take a look.

**Comment by kristijanhusak** [comment]
I just pushed a fix. Output window height is now properly calculated, so notification should be above it even when window is resized.
Also, I added an option `g:db_ui_force_echo_notifications` which will echo all notifications instead of showing them in popup, when the setting is enabled (disabled by default).

**Comment by przepompownia** [comment]
Notifications now are displayed on the drawer space. `g:db_ui_force_echo_notifications` works as expected. Thanks! :tada:
