### ISSUE TITLE
Drawer: need a mapping that jumps to the current list node

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#96]
Having the cursor at the particular table I need a map that jumps to `Tables` node etc. 

Goal: Lynx-like motion (Midnight Commander have such option).

**Comment by kristijanhusak** [comment]
I introduced several mappings for going around the tree:

`J` - Go to next sibling
`K` - Go to previous sibling
`<C-j>` - Go to last sibling
`<C-k>` - Go to last sibling
`<C-p>` - Go to parent node
`<C-n>` - Go to child node (only for toggleable entries)

I would appreciate if you would pull latest master and give it a try.

**Comment by przepompownia** [comment]
It's much more than I proposed! Thanks! :beer: 

```vim
  nmap <buffer> <Left> <Plug>(DBUI_GotoParentNode)<CR>
  nmap <buffer> <Right> <Plug>(DBUI_GotoChildNode)
```
With the above mapping I have Lynx-like motion.

`<Plug>(DBUI_GotoLastSibling)` works only on leaf nodes. I cannot switch to the last table node with it.

**Comment by kristijanhusak** [comment]
I pushed a fix, should be working now.

**Comment by przepompownia** [comment]
Confirmed
