### ISSUE TITLE
E21 Cannot make changes, 'modifiable' is off

### ISSUE THREAD

**Issue by pkail** [kristijanhusak/vim-dadbod-ui#98]
I entered :DBUI; a menu popped up.  I pressed ?, which suggested that I type A.  I pressed A and got this error message.
I tried entering the connection URL directly.  I also got this message.
I restarted Vim.  Same problem.

**Comment by kristijanhusak** [comment]
did you press small `a` or big `A` ?
What you mean by "Entering the connection URL directly" ?

**Comment by pkail** [comment]
I was using A.
>>What you mean by "Entering the connection URL directly" ?
It says (+) Add connection.  I thought that this might mean that you can add a connection string as a command.  I can see that this is not the case.
Typing A now gives me a prompt which allows me to enter the URL and database name.   However, I then get:

[DBUI] Vim(if):E117: Unknown function: trim

**Comment by kristijanhusak** [comment]
Seems like you have a bit outdated vim version. Do you have version `8.1+` ?

**Comment by pkail** [comment]
No, I'm using 8.0.  I'll try the most recent version.  Thanks.

**Comment by pkail** [comment]
When I run :DBUI and press A I get:

E21: Cannot make changes, 'modifiable' is off

This is with Vim 8.2.

**Comment by kristijanhusak** [comment]
What happens if you select "Add Connection" ?
What's your output for `:map A` while you're in the DBUI window?
Did you add any dadbod-ui specific configuration?

**Comment by pkail** [comment]
>>What happens if you select "Add Connection" ?
How do I do that?  I've tried highlighting the + next to Add Connection and pressing tab, Enter, etc.  Nothing seems to do anything.
:map A produces 'No mapping found'.
There are no dadbod-ui specific configurations.

**Comment by kristijanhusak** [comment]
Seems like none of the mappings are attached for you.
Whats your output for this:
```
:echo g:db_ui_disable_mappings
```

**Comment by pkail** [comment]
0

**Comment by kristijanhusak** [comment]
check the edit part in previous comment.

**Comment by pkail** [comment]
Sorry, I missed that.  No, I don't.

**Comment by kristijanhusak** [comment]
You need to have that so mappings can be attached. You can also use `:DBUIAddConnection` if you want.

**Comment by pkail** [comment]
It works now, thanks.
