### ISSUE TITLE
Help needed: making autocomletion work

### ISSUE THREAD

**Issue by evdoks** [kristijanhusak/vim-dadbod-ui#99]
Really love your plugin! However, autocompletion seems not to be working out of the box.

I am using a VIM. For code autocompletion I have YouCompleteMe plugin installed.

 Any ideas on how to start debugging the issue?

**Comment by kristijanhusak** [comment]
Did you install https://github.com/kristijanhusak/vim-dadbod-completion ?

YouCompleteMe is not supported out of the box. Check what is supported on the dadbod-completion readme.

**Comment by evdoks** [comment]
Thanks!

**Comment by kristijanhusak** [comment]
You should be able to setup omnifunc with YCM
